# 🔹 UFC Fight Predictor v2 Model Training

<div style="text-align: center;">
  🔹 <img src="../img/ufc_logo.png" width="50" /> 🔹
</div>

#  Import Libraries and Setup Environment

In [1]:
# Import necessary libraries
import os
import sys
import pandas as pd
from autogluon.tabular import TabularDataset, TabularPredictor
pd.set_option('display.max_colwidth', 200) 

# Get the current working directory
current_dir = os.getcwd()

# Navigate to the project root
project_root = os.path.abspath(os.path.join(current_dir, '..'))

# Import from /src
sys.path.append(os.path.join(project_root))
from src.io_model import *
from src.helpers import prepare_modeling_df

<div style="text-align: center;">
  🔹 <img src="../img/ufc_logo.png" width="50" /> 🔹
</div>

#  Load Data

In [27]:
# Define the path to the CSV file
file_path = os.path.join(project_root, 'data', 'processed', 'ufc_fte.csv')

# Load the CSV into a DataFrame
try:
    ufc_df = pd.read_csv(file_path)
    logger.info(f"✅ Data successfully loaded: {ufc_df.shape[0]} rows, {ufc_df.shape[1]} columns.")
except Exception as e:
    logger.error(f"❌ Error loading data: {e}")

# ⚙️ Calibration

In [28]:
ufc_data = prepare_modeling_df(
    ufc_df,
    start_date="2016-01-01",
    drop_r=True, drop_b=True,
    keep_last=False, keep_career=True, keep_ema=True,
    compute_dif=True,
    drop_cols=['title_fight', 'date', 'b_momentum', 'r_momentum'],
    keep_cols=['b_stance','b_momentum_ema', 'r_momentum_ema'],
    min_total_fights=2,
    as_ufcdata=True,
    skip_diff_bases=["momentum_ema"]
)

[INFO] Filtered by min_total_fights=2: 2911 → 2911 rows

In [29]:
ufc_data

📊 UFC Dataset Summary
----------------------------------------
🧪 Total samples       : 2911
🧪 Train/Test split    : 2328 / 583
🧪 Total features      : 72

🔢 Numerical features  : 69
🔠 Categorical features: 3
    - Binary           : 1
    - Multiclass       : 2

🔠 Categorical feature names (all):
      b_stance, division, total_rounds

   • Binary categorical features:
      total_rounds

   • Multiclass categorical features:
      b_stance, division

🏷 Label distribution (raw):
   - Class 0: 1638 (56.3%)
   - Class 1: 1273 (43.7%)

✅ No missing values detected

📈 Feature summary statistics (train set):
                              mean       std       min       max
r_momentum_ema               0.160     0.553    -0.983     1.000
b_momentum_ema               0.243     0.549    -0.948     1.000
BodySApM_career_dif          0.017     0.512    -3.311     2.562
BodySApM_ema_dif            -0.007     0.629    -3.920     2.828
BodySLpM_career_dif          0.012     0.673    -3.910     7.071
BodySLpM_ema_dif            -0.003     0.747    -5.678     5.462
ClinchSApM_career_dif       -0.001     0.618   -12.476     5.997
ClinchSApM_ema_dif          -0.009     0.709    -9.857     6.391
ClinchSLpM_career_dif       -0.001     0.813   -13.790     7.481
ClinchSLpM_ema_dif           0.025     0.853   -11.169    10.851
CtrlpM_career_dif           -0.123    11.536   -46.655    53.992
CtrlpM_ema_dif               0.410    12.431   -51.673    56.363
DistSApM_career_dif          0.044     1.684    -7.720     9.365
DistSApM_ema_dif            -0.096     2.005    -9.202    10.548
DistSLpM_career_dif          0.027     1.892   -21.060     7.793
DistSLpM_ema_dif            -0.013     2.178   -17.979     9.277
GroundSApM_career_dif        0.007     0.902    -9.431    13.982
GroundSApM_ema_dif          -0.014     1.180    -8.991    17.773
GroundSLpM_career_dif        0.057     1.642   -12.236    21.846
GroundSLpM_ema_dif           0.115     1.693   -14.184    17.936
HeadSApM_career_dif          0.014     1.734   -15.241    19.743
HeadSApM_ema_dif            -0.118     2.148   -13.672    17.886
HeadSLpM_career_dif          0.081     2.408   -20.652    21.765
HeadSLpM_ema_dif             0.137     2.598   -21.775    20.075
LegSApM_career_dif           0.019     0.497    -2.572     2.634
LegSApM_ema_dif              0.007     0.589    -3.261     2.727
LegSLpM_career_dif          -0.009     0.632    -2.825     3.104
LegSLpM_ema_dif             -0.008     0.722    -3.590     3.817
OpCtrlpM_career_dif          0.367     9.438   -32.604    42.809
OpCtrlpM_ema_dif             0.244    10.702   -37.225    40.536
SApM_career_dif              0.050     2.090   -17.056    19.899
SApM_ema_dif                -0.118     2.581   -16.239    18.872
SLpM_career_dif              0.083     2.760   -22.116    20.674
SLpM_ema_dif                 0.126     2.999   -21.694    23.196
Str_Acc_career_dif           0.414    11.206   -51.024    38.770
Str_Acc_ema_dif              0.638    12.602   -47.994    42.556
Str_Def_career_dif          -0.423    11.251   -58.058    47.358
Str_Def_ema_dif              0.369    12.620   -72.365    42.764
Sub_Avg_career_dif          -0.013     1.868   -15.237    19.250
Sub_Avg_ema_dif             -0.001     1.991   -16.440    16.740
TD_Acc_career_dif           -1.019    25.445  -100.000    87.500
TD_Acc_ema_dif               0.214    29.108  -100.000    92.800
TD_Avg_career_dif           -0.062     2.221   -21.454    10.763
TD_Avg_ema_dif               0.036     2.440   -25.345    17.149
TD_Def_career_dif            0.079    29.726  -100.000   100.000
TD_Def_ema_dif               0.747    34.739  -100.000   100.000
TSApM_career_dif             0.066     2.313   -21.496    19.190
TSApM_ema_dif               -0.124     2.835   -17.357    22.299
TSLpM_career_dif             0.125     3.141   -22.918    19.954
TSLpM_ema_dif                0.211     3.409   -20.282    22.991
TStr_Acc_career_dif          0.503    12.091   -50.382    53.505
TStr_Acc_ema_dif             0.817    13.729   -47.223    57.920
TStr_Def_career_dif         -0.332    12.644   -54.994    51.430
TStr_Def_ema_dif             0.241    13.818   -66.498    51.340
age_dif                     -0.748     5.265   -17.000    14.000
avg_time_career_dif         -0.322     3.948   -13.490    13.983
avg_time_ema_dif            -0.592     4.932   -16.896    15.231
current_lose_streak_dif     -0.138     1.068    -6.000     5.000
current_win_streak_dif       0.097     2.354   -18.000    10.000
days_since_debut_dif      -427.844  1462.736 -7792.000  4943.000
days_since_last_fight_dif   -1.521   238.377 -2912.000  2694.000
finish_rate_dif             -0.016     0.419    -1.000     1.000
height_dif                   0.088     6.145   -25.400    20.320
ko_per_fight_dif            -0.002     0.251    -1.000     1.000
reach_dif                   -0.153     8.014   -25.400    25.400
reach_height_ratio_dif      -0.001     0.038    -0.158     0.136
sub_per_fight_dif           -0.010     0.234    -1.000     1.000
total_fights_dif            -2.421     7.750   -34.000    27.000
win_ratio_dif               -0.017     0.238    -1.000     0.833

⚙️ Preprocessing status:
   - Standardized?     : ❌
   - Correlation cached (raw)      : ❌
   - Correlation cached (processed): ❌
----------------------------------------

<div style="text-align: center;">
  🔹 <img src="../img/ufc_logo.png" width="50" /> 🔹
</div>

# 🔹 UFC Machine Learning Training

### 🚀 AutoGluon Training

In [30]:
train_data = ufc_data.get_df_train()
train_data

               division total_rounds  b_stance  r_momentum_ema  \
1191        heavyweight        Three  Orthodox       -0.693359
1434       welterweight        Three  Orthodox        0.869629
1759       middleweight        Three  Orthodox        0.406250
1074              women        Three  Orthodox        0.875000
400        middleweight        Three  Orthodox        0.671875
800        middleweight        Three    Switch       -0.188599
55          lightweight        Three  Southpaw       -0.412201
1586       welterweight        Three  Orthodox        0.169434
448         heavyweight        Three  Orthodox       -0.750000
179        welterweight        Three  Southpaw        0.703125
1492       middleweight         Five  Southpaw        0.749619
1519        lightweight        Three  Southpaw       -0.500065
647        welterweight        Three  Southpaw       -0.843750
2100              women        Three  Orthodox       -0.285156
1803              women        Three  Orthodox       -0.265625
1637        lightweight        Three  Orthodox        0.437500
594        middleweight        Three  Orthodox        0.809814
1048       middleweight        Three  Orthodox       -0.250488
2716        heavyweight        Three  Orthodox        0.225830
2074       welterweight        Three  Orthodox       -0.252262
505         lightweight        Three  Southpaw       -0.005035
2537       bantamweight        Three  Orthodox        0.417236
891         lightweight        Three  Orthodox        0.312500
903        welterweight        Three  Orthodox        0.863770
387         heavyweight         Five  Orthodox        0.933350
1428      featherweight        Three    Switch        0.125000
2109       bantamweight        Three  Orthodox        0.060535
2731        lightweight        Three  Orthodox       -0.298218
176        middleweight        Three  Orthodox       -0.511810
532        middleweight         Five  Southpaw       -0.020762
603         lightweight        Three  Orthodox       -0.916584
1456       bantamweight        Three  Southpaw       -0.507812
1453              women         Five  Orthodox        0.999451
2841       bantamweight         Five  Orthodox       -0.097717
440         lightweight        Three  Orthodox        0.734375
1024        heavyweight        Three  Orthodox        0.250000
1440      featherweight        Three  Southpaw        0.250000
2273       bantamweight         Five    Switch        0.997677
129        welterweight        Three  Orthodox        0.498748
2003      featherweight         Five  Southpaw       -0.285645
2511       welterweight        Three  Orthodox        0.625000
1044              women        Three  Orthodox        0.250000
586               women        Three  Orthodox       -0.335938
82            flyweight        Three  Orthodox        0.421875
223         heavyweight        Three  Southpaw        0.250000
337       featherweight        Three  Orthodox        0.937500
2261  light heavyweight        Three  Orthodox        0.795166
1129       bantamweight        Three  Orthodox        0.357422
1875       welterweight        Three  Orthodox        0.830926
64         welterweight        Three  Orthodox        0.656250
2403       middleweight        Three  Orthodox        0.359375
584        welterweight        Three  Orthodox        0.410156
1496              women         Five  Orthodox        0.981934
1398       bantamweight        Three  Orthodox       -0.261719
2873              women         Five  Southpaw        0.421387
963         lightweight        Three  Orthodox        0.912012
2417        lightweight        Three  Orthodox       -0.023438
370        welterweight        Three  Southpaw        0.429688
884         lightweight        Three  Orthodox       -0.031738
1695          flyweight        Three    Switch        0.125000
1463       bantamweight        Three  Orthodox        0.703125
2628              women        Three  Orthodox        0.437500
1454  light heavyweight         Five    Switch        0.934174
1556  light heavyweight        Three  Orthodox        0.062500
1262      featherweight        Three  Orthodox       -0.132812
2475       middleweight        Three  Orthodox        0.750000
484         lightweight        Three  Orthodox       -0.912842
2507              women        Three  Orthodox        0.453125
2158        lightweight        Three  Orthodox        0.175781
169        welterweight        Three  Orthodox       -0.332674
1653       welterweight        Three  Southpaw        0.209961
2060              women        Three  Orthodox        0.625000
1290       middleweight        Three  Orthodox        0.601425
1042       bantamweight        Three  Orthodox        0.453125
2780        lightweight        Three  Orthodox       -0.377686
1527        heavyweight         Five  Orthodox       -0.257812
752        middleweight        Three  Orthodox       -0.562500
219           flyweight        Three  Orthodox       -0.085938
1547        lightweight        Three  Southpaw       -0.265625
101        middleweight        Three  Orthodox        0.828125
2491       bantamweight        Three  Southpaw       -0.112550
2748        heavyweight        Three  Orthodox       -0.505859
2245       welterweight        Three  Southpaw       -0.285156
601         lightweight        Three  Orthodox       -0.593750
567       featherweight        Three  Southpaw        0.248047
528         heavyweight         Five  Orthodox        0.373840
585       featherweight        Three  Orthodox       -0.031250
975         lightweight        Three  Orthodox        0.999481
1061        lightweight        Three  Orthodox        0.980469
287       featherweight         Five  Orthodox        0.996979
57        featherweight        Three  Orthodox       -0.312500
1863       bantamweight        Three  Orthodox       -0.068359
2116       bantamweight        Three  Southpaw        0.929688
69         welterweight        Three  Southpaw        0.250000
1981        lightweight        Three  Southpaw       -0.632812
1584       bantamweight        Three  Orthodox        0.875000
907        welterweight        Three  Orthodox        0.976562
495        welterweight         Five  Southpaw       -0.515664
439        welterweight         Five  Orthodox        0.685547
1899        lightweight        Three  Southpaw       -0.031250
2658       middleweight         Five  Orthodox        0.957031
2766       bantamweight        Three  Orthodox       -0.755981
479         lightweight        Three  Southpaw        0.750000
214       featherweight        Three  Orthodox       -0.105469
871        bantamweight         Five  Orthodox        0.937134
1715          flyweight        Three  Orthodox        0.367188
2450        heavyweight        Three  Southpaw        0.750000
384       featherweight        Three  Orthodox        0.437500
1927        lightweight        Three  Southpaw        0.250000
2593              women        Three  Orthodox       -0.314453
2143          flyweight        Three  Orthodox        0.609375
2114        heavyweight        Three  Southpaw        0.355347
2363       bantamweight        Three    Switch        0.140503
2707       welterweight         Five  Orthodox        0.984375
1638       middleweight        Three  Southpaw       -0.344727
1479       bantamweight        Three  Orthodox        0.375000
1472              women        Three  Orthodox       -0.777832
1791        heavyweight        Three  Southpaw       -0.537109
2568      featherweight        Three    Switch       -0.382812
2821        lightweight        Three  Southpaw        0.431062
1385       welterweight        Three  Southpaw        0.750000
1241      featherweight        Three    Switch        0.234375
2023              women        Three  Orthodox        0.025269
27            flyweight        Three  Southpaw        0.812500
2102       middleweight        Three    Switch       -0.024911
807         heavyweight         Five  Orthodox        0.983887
949               women        Three  Orthodox       -0.681641
302           flyweight        Three  Orthodox       -0.580078
1972              women        Three  Orthodox       -0.312500
1908      featherweight        Three  Orthodox        0.312500
602        middleweight         Five  Southpaw       -0.001953
2861              women        Three  Orthodox        0.220573
1148  light heavyweight        Three  Orthodox        0.117188
614        welterweight        Three  Southpaw       -0.275513
2740          flyweight        Three  Orthodox        0.718750
1592  light heavyweight        Three  Orthodox        0.218750
2687       welterweight         Five    Switch       -0.330220
8           heavyweight        Three    Switch       -0.266357
1126        lightweight        Three  Orthodox        0.956006
1228        heavyweight         Five  Southpaw       -0.195656
924        middleweight        Three  Southpaw        0.250000
933           flyweight        Three  Orthodox        0.115967
1403       welterweight        Three  Orthodox        0.187500
575        welterweight        Three  Orthodox       -0.750000
1510       welterweight        Three  Orthodox       -0.886246
1269      featherweight        Three  Orthodox       -0.626953
322         lightweight        Three  Southpaw        0.681595
2400              women        Three  Orthodox        0.710938
240       featherweight        Three  Orthodox       -0.282227
343         lightweight        Three  Southpaw        0.679184
2835       middleweight        Three  Southpaw        0.750000
2099       middleweight        Three  Orthodox       -0.156250
1377              women         Five  Orthodox        0.963867
2627       bantamweight        Three  Orthodox        0.687500
1426       middleweight        Three  Orthodox       -0.521519
2513       bantamweight        Three  Orthodox       -0.132812
1273       bantamweight        Three  Southpaw        0.234375
2807      featherweight         Five  Orthodox        0.245544
1857        lightweight        Three  Orthodox       -0.062500
997           flyweight        Three  Southpaw        0.920532
1115  light heavyweight        Three  Orthodox        0.795776
1489        heavyweight        Three  Orthodox        0.750000
1712       bantamweight        Three  Orthodox       -0.383148
1821       middleweight        Three  Southpaw        0.445160
274        welterweight        Three  Orthodox        0.138649
1723        lightweight        Three  Southpaw       -0.506104
1656        heavyweight        Three  Orthodox        0.409210
991        welterweight        Three  Orthodox       -0.322266
693         heavyweight        Three  Orthodox       -0.750000
141               women         Five  Orthodox        0.968750
936               women        Three  Orthodox       -0.250000
1063  light heavyweight        Three  Orthodox       -0.378906
1617  light heavyweight        Three  Orthodox       -0.671875
1123       welterweight        Three  Orthodox        0.405273
1103       welterweight         Five  Orthodox        0.562124
630         heavyweight         Five  Orthodox        0.686920
2698              women        Three  Orthodox       -0.410645
840   light heavyweight        Three  Orthodox       -0.579102
754        welterweight        Three  Orthodox        0.896484
1316       bantamweight        Three  Orthodox       -0.250000
2240              women        Three  Orthodox       -0.195312
2022       bantamweight        Three  Southpaw        0.339844
503        middleweight        Three  Orthodox        0.835938
1468       middleweight        Three  Orthodox        0.609375
1186       welterweight        Three  Orthodox        0.250000
391        middleweight        Three  Orthodox       -0.250000
2490       middleweight        Three  Southpaw       -0.378273
1198       welterweight        Three  Orthodox       -0.782318
368        middleweight        Three  Orthodox        0.312500
1895              women        Three  Orthodox       -0.195312
1381              women        Three  Orthodox       -0.312500
1624              women         Five  Orthodox        0.990967
1867              women        Three  Orthodox       -0.507812
1474        lightweight        Three  Orthodox       -0.750000
2727       middleweight        Three  Southpaw       -0.316406
2142              women        Three  Orthodox        0.593750
908        welterweight        Three  Orthodox        0.359375
1872       bantamweight        Three  Orthodox       -0.700409
2118              women        Three  Orthodox       -0.831207
2503        heavyweight         Five  Orthodox       -0.453873
1914      featherweight        Three    Switch        0.233398
1982       middleweight        Three  Orthodox        0.722580
510        welterweight        Three  Orthodox       -0.252441
2890              women        Three  Orthodox       -0.250000
1681              women        Three  Orthodox       -0.676636
1679       welterweight         Five  Orthodox        0.999939
1028        lightweight        Three  Orthodox        0.263972
86          lightweight        Three  Orthodox       -0.238770
926         lightweight         Five  Orthodox        0.229949
2001       bantamweight         Five  Orthodox        0.990707
2028        lightweight        Three  Orthodox       -0.063509
2773      featherweight        Three  Orthodox        0.169800
50    light heavyweight        Three  Orthodox        0.414062
2147       bantamweight        Three  Orthodox       -0.691574
2279  light heavyweight        Three  Orthodox       -0.551046
485        welterweight        Three  Orthodox       -0.367188
231        bantamweight        Three  Orthodox        0.250000
181        welterweight        Three  Orthodox        0.832996
923               women        Three  Orthodox       -0.166992
1270      featherweight        Three  Orthodox       -0.390625
1167       middleweight        Three  Orthodox       -0.562500
2334        lightweight        Three  Orthodox        0.750000
2078              women        Three  Orthodox        0.489380
155           flyweight        Three    Switch        0.843750
1578       middleweight        Three  Orthodox       -0.250000
2088        lightweight         Five  Orthodox        0.999390
1012       middleweight        Three  Southpaw       -0.406250
119       featherweight        Three  Orthodox        0.993958
445       featherweight        Three  Orthodox       -0.187866
2112       bantamweight        Three  Orthodox       -0.250000
395        bantamweight        Three  Orthodox        0.656250
1659              women        Three  Orthodox       -0.281250
2346              women        Three  Orthodox       -0.689209
2637       welterweight        Three  Orthodox        0.750000
2538          flyweight         Five  Orthodox        0.116699
281        middleweight        Three  Southpaw       -0.062500
597        welterweight        Three  Orthodox        0.214844
428               women        Three  Orthodox        0.468750
2517       middleweight         Five  Orthodox       -0.094059
1888          flyweight        Three  Southpaw       -0.750000
1210      featherweight        Three    Switch        0.875000
419        middleweight        Three  Southpaw       -0.229533
120       featherweight        Three  Orthodox        0.750000
1964      featherweight        Three  Orthodox       -0.162109
1179  light heavyweight         Five  Orthodox        0.897888
2826          flyweight        Three  Orthodox       -0.828979
1485       middleweight         Five  Orthodox        0.912109
808        welterweight        Three  Orthodox       -0.439458
1229              women        Three  Orthodox        0.354492
490           flyweight        Three  Orthodox       -0.750000
2181        lightweight        Three  Southpaw       -0.753052
751         lightweight         Five  Orthodox       -0.625000
931         lightweight         Five  Southpaw        0.999811
2037  light heavyweight        Three  Southpaw        0.226562
1326       bantamweight        Three  Southpaw        0.343750
543               women        Three  Orthodox        0.734375
1522              women        Three  Orthodox       -0.312500
1583       bantamweight         Five  Orthodox        0.746094
160        middleweight        Three  Orthodox       -0.836262
58         middleweight        Three  Orthodox        0.437500
2419          flyweight         Five  Southpaw       -0.143097
2436       welterweight        Three    Switch       -0.156533
1494       welterweight        Three  Orthodox       -0.222790
2648       welterweight        Three  Southpaw       -0.400884
1535       welterweight        Three  Orthodox       -0.109469
2322       middleweight        Three  Orthodox       -0.500008
1652       middleweight        Three  Orthodox       -0.298828
1506       middleweight        Three  Southpaw        0.750000
471           flyweight        Three  Southpaw       -0.515625
1011      featherweight        Three  Orthodox        0.416748
1588          flyweight        Three  Southpaw       -0.667969
1782  light heavyweight        Three  Southpaw        0.180664
1246       bantamweight        Three  Orthodox       -0.625000
1614       welterweight        Three  Orthodox        0.364990
1733        heavyweight        Three  Orthodox       -0.333984
1328       middleweight        Three  Orthodox        0.726562
2081        heavyweight         Five  Orthodox       -0.630983
2755       welterweight        Three  Orthodox        0.341605
1443        heavyweight        Three  Orthodox       -0.196411
2057       bantamweight        Three  Orthodox        0.312500
1182       welterweight        Three    Switch        0.450928
7           lightweight        Three  Southpaw        0.421875
1299       bantamweight        Three  Orthodox        0.167709
1542      featherweight        Three  Orthodox        0.937500
1511              women         Five  Orthodox        0.343750
1127      featherweight        Three  Orthodox       -0.296875
1163              women        Three  Orthodox       -0.551758
930        middleweight        Three  Orthodox       -0.324219
1164          flyweight        Three  Orthodox       -0.250000
2198              women        Three  Orthodox        0.609375
2520        lightweight         Five  Southpaw        0.999847
162               women         Five  Southpaw       -0.062500
2795  light heavyweight        Three  Orthodox       -0.377057
2660        heavyweight        Three  Orthodox       -0.750000
2277              women        Three  Southpaw       -0.750000
294        bantamweight        Three  Orthodox        0.173828
2452       middleweight        Three  Orthodox       -0.439453
434         heavyweight        Three  Orthodox       -0.829147
2645              women        Three  Orthodox       -0.380127
171        bantamweight        Three  Orthodox       -0.693359
124        welterweight        Three  Southpaw        0.718750
886        bantamweight        Three    Switch       -0.329163
447        welterweight        Three  Orthodox        0.742188
1104        lightweight        Three  Southpaw        0.156250
1459          flyweight        Three  Orthodox       -0.125000
78                women        Three  Orthodox        0.625000
611         heavyweight        Three  Orthodox       -0.010010
721               women        Three  Orthodox       -0.781250
737           flyweight        Three  Orthodox        0.647217
835        welterweight        Three  Orthodox       -0.095703
114        middleweight        Three  Orthodox        0.514862
2673       bantamweight        Three  Orthodox        0.898438
2753      featherweight        Three  Orthodox        0.437500
1419  light heavyweight        Three  Orthodox       -0.277344
636               women         Five  Orthodox        0.726562
1699       middleweight        Three  Orthodox       -0.843750

In [31]:
predictor = TabularPredictor(label='label', path = '../models').fit(train_data, presets='good')

Warning: path already exists! This predictor may overwrite an existing predictor! path="../models"
Preset alias specified: 'good' maps to 'good_quality'.
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.3.1
Python Version:     3.10.13
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP PREEMPT_DYNAMIC Thu Jul 17 17:57:16 UTC 2025
CPU Count:          24
Memory Avail:       7.93 GB / 15.51 GB (51.1%)
Disk Space Avail:   185.10 GB / 236.89 GB (78.1%)
===================================================
Presets specified: ['good']
Setting dynamic_stacking from 'auto' to True. Reason: Enable dynamic_stacking when use_bag_holdout is disabled. (use_bag_holdout=False)
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=8, num_bag_sets=1
Note: `save_bag_folds=False`! This will greatly reduce peak disk usage during fit (by ~8x), but runs the risk of an out-of-memory error during model refit if memory is small relative to the data size.
	You can avoid this risk by setting `save_bag_folds=True`.
DyStack is enabled (dynamic_stacking=True). AutoGluon will try to determine whether the input data is affected by stacked overfitting and enable or disable stacking as a consequence.
	This is used to identify the optimal `num_stack_levels` value. Copies of AutoGluon will be fit on subsets of the data. Then holdout validation data is used to detect stacked overfitting.
	Running DyStack for up to 900s of the 3600s of remaining time (25%).
		Context path: "/home/mlioi/ufc-predictor-v2/models/ds_sub_fit/sub_fit_ho"
Leaderboard on holdout data (DyStack):
                           model  score_holdout  score_val eval_metric  pred_time_test  pred_time_val   fit_time  pred_time_test_marginal  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0   RandomForestEntr_BAG_L1_FULL       0.640927   0.607057    accuracy        0.099044       0.186633   0.755479                 0.099044                0.186633           0.755479            1       True          4
1     ExtraTreesEntr_BAG_L1_FULL       0.637066   0.606090    accuracy        0.088659       0.183190   0.640054                 0.088659                0.183190           0.640054            1       True          7
2   RandomForestGini_BAG_L1_FULL       0.637066   0.602223    accuracy        0.105319       0.181437   0.848118                 0.105319                0.181437           0.848118            1       True          3
3     ExtraTreesGini_BAG_L1_FULL       0.633205   0.606090    accuracy        0.099193       0.184827   0.778105                 0.099193                0.184827           0.778105            1       True          6
4      LightGBMLarge_BAG_L2_FULL       0.633205   0.646689    accuracy        0.472486            NaN  32.330884                 0.010904                     NaN          22.579461            2       True         23
5            XGBoost_BAG_L1_FULL       0.629344   0.637989    accuracy        0.009040            NaN   0.487098                 0.009040                     NaN           0.487098            1       True          9
6     ExtraTreesGini_BAG_L2_FULL       0.629344   0.614306    accuracy        0.561335            NaN  10.423388                 0.099754                0.195304           0.671964            2       True         18
7     ExtraTreesEntr_BAG_L2_FULL       0.629344   0.617690    accuracy        0.566279            NaN  10.403247                 0.104697                0.182788           0.651824            2       True         19
8           CatBoost_BAG_L1_FULL       0.625483   0.641373    accuracy        0.009596            NaN   1.363117                 0.009596                     NaN           1.363117            1       True          5
9       WeightedEnsemble_L2_FULL       0.625483   0.641373    accuracy        0.011408            NaN   1.538252                 0.001812                     NaN           0.175135            2       True         12
10  RandomForestGini_BAG_L2_FULL       0.625483   0.623006    accuracy        0.553084            NaN  10.498753                 0.091502                0.181195           0.747330            2       True         15
11          CatBoost_BAG_L2_FULL       0.621622   0.657322    accuracy        0.470319            NaN  10.616808                 0.008738                     NaN           0.865384            2       True         17
12      WeightedEnsemble_L3_FULL       0.621622   0.657322    accuracy        0.472212            NaN  10.860808                 0.001893                     NaN           0.244000            3       True         24
13  RandomForestEntr_BAG_L2_FULL       0.617761   0.634123    accuracy        0.548288            NaN  10.525977                 0.086706                0.188730           0.774554            2       True         16
14    NeuralNetTorch_BAG_L1_FULL       0.613900   0.639439    accuracy        0.018884            NaN   1.800309                 0.018884                     NaN           1.800309            1       True         10
15     LightGBMLarge_BAG_L1_FULL       0.610039   0.628323    accuracy        0.008660            NaN   9.574953                 0.008660                     NaN           9.574953            1       True         11
16        LightGBMXT_BAG_L2_FULL       0.610039   0.644273    accuracy        0.467745            NaN  11.025353                 0.006164                     NaN           1.273929            2       True         13
17        LightGBMXT_BAG_L1_FULL       0.598456   0.639439    accuracy        0.007547            NaN   1.269793                 0.007547                     NaN           1.269793            1       True          1
18   NeuralNetFastAI_BAG_L2_FULL       0.594595   0.640406    accuracy        0.484756            NaN  11.216373                 0.023174                     NaN           1.464950            2       True         20
19          LightGBM_BAG_L2_FULL       0.590734   0.653456    accuracy        0.467200            NaN  12.068763                 0.005619                     NaN           2.317340            2       True         14
20           XGBoost_BAG_L2_FULL       0.590734   0.650072    accuracy        0.471864            NaN  10.289900                 0.010283                     NaN           0.538477            2       True         21
21          LightGBM_BAG_L1_FULL       0.586873   0.631223    accuracy        0.004209            NaN   0.962065                 0.004209                     NaN           0.962065            1       True          2
22   NeuralNetFastAI_BAG_L1_FULL       0.579151   0.618173    accuracy        0.020090            NaN   0.847286                 0.020090                     NaN           0.847286            1       True          8
23    NeuralNetTorch_BAG_L2_FULL       0.579151   0.646206    accuracy        0.483267            NaN  11.748131                 0.021686                     NaN           1.996708            2       True         22
	0	 = Optimal   num_stack_levels (Stacked Overfitting Occurred: True)
	202s	 = DyStack   runtime |	3398s	 = Remaining runtime
Starting main fit with num_stack_levels=0.
	For future fit calls on this dataset, you can skip DyStack to save time: `predictor.fit(..., dynamic_stacking=False, num_stack_levels=0)`
Beginning AutoGluon training ... Time limit = 3398s
AutoGluon will save models to "/home/mlioi/ufc-predictor-v2/models"
Train Data Rows:    2328
Train Data Columns: 72
Label Column:       label
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    7832.06 MB
	Train Data (Original)  Memory Usage: 1.66 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 66 | ['r_momentum_ema', 'b_momentum_ema', 'BodySApM_career_dif', 'BodySApM_ema_dif', 'BodySLpM_career_dif', ...]
		('int', [])    :  3 | ['current_lose_streak_dif', 'current_win_streak_dif', 'total_fights_dif']
		('object', []) :  3 | ['division', 'total_rounds', 'b_stance']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  :  2 | ['division', 'b_stance']
		('float', [])     : 66 | ['r_momentum_ema', 'b_momentum_ema', 'BodySApM_career_dif', 'BodySApM_ema_dif', 'BodySLpM_career_dif', ...]
		('int', [])       :  3 | ['current_lose_streak_dif', 'current_win_streak_dif', 'total_fights_dif']
		('int', ['bool']) :  1 | ['total_rounds']
	0.1s = Fit runtime
	72 features in original data used to generate 72 features in processed data.
	Train Data (Processed) Memory Usage: 1.23 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.14s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'max_depth': 15, 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'max_depth': 15, 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'max_depth': 15, 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'max_depth': 15, 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'max_depth': 15, 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'max_depth': 15, 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 3397.48s of the 3397.47s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=3, gpus=0, memory=0.31%)
	0.6473	 = Validation score   (accuracy)
	2.37s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 3393.24s of the 3393.24s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=3, gpus=0, memory=0.30%)
	0.6448	 = Validation score   (accuracy)
	4.33s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestGini_BAG_L1 ... Training model for up to 3387.08s of the 3387.08s of remaining time.
/home/mlioi/anaconda3/envs/ag/lib/python3.10/site-packages/sklearn/base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
  warnings.warn(
	0.61	 = Validation score   (accuracy)
	0.77s	 = Training   runtime
	0.19s	 = Validation runtime
Fitting model: RandomForestEntr_BAG_L1 ... Training model for up to 3386.06s of the 3386.06s of remaining time.
/home/mlioi/anaconda3/envs/ag/lib/python3.10/site-packages/sklearn/base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
  warnings.warn(
	0.6014	 = Validation score   (accuracy)
	0.77s	 = Training   runtime
	0.19s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 3385.04s of the 3385.04s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=3, gpus=0, memory=5.44%)
	0.6422	 = Validation score   (accuracy)
	13.59s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: ExtraTreesGini_BAG_L1 ... Training model for up to 3369.67s of the 3369.67s of remaining time.
/home/mlioi/anaconda3/envs/ag/lib/python3.10/site-packages/sklearn/base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
  warnings.warn(
	0.6108	 = Validation score   (accuracy)
	0.68s	 = Training   runtime
	0.19s	 = Validation runtime
Fitting model: ExtraTreesEntr_BAG_L1 ... Training model for up to 3368.74s of the 3368.74s of remaining time.
/home/mlioi/anaconda3/envs/ag/lib/python3.10/site-packages/sklearn/base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
  warnings.warn(
	0.613	 = Validation score   (accuracy)
	0.66s	 = Training   runtime
	0.18s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 3367.84s of the 3367.84s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=3, gpus=0, memory=0.16%)
	0.6194	 = Validation score   (accuracy)
	6.04s	 = Training   runtime
	0.13s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 3360.06s of the 3360.06s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=3, gpus=0, memory=0.78%)
	0.6409	 = Validation score   (accuracy)
	6.06s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 3351.96s of the 3351.96s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=3, gpus=0, memory=0.10%)
	0.6409	 = Validation score   (accuracy)
	9.52s	 = Training   runtime
	0.23s	 = Validation runtime
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 3340.69s of the 3340.69s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=3, gpus=0, memory=0.98%)
	0.6422	 = Validation score   (accuracy)
	16.54s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 3322.29s of remaining time.
	Ensemble Weights: {'LightGBMXT_BAG_L1': 1.0}
	0.6473	 = Validation score   (accuracy)
	0.16s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 75.5s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 7024.1 rows/s (291 batch size)
Automatically performing refit_full as a post-fit operation (due to `.fit(..., refit_full=True)`
Refitting models via `predictor.refit_full` using all of the data (combined train and validation)...
	Models trained in this way will have the suffix "_FULL" and have NaN validation score.
	This process is not bound by time_limit, but should take less time than the original `predictor.fit` call.
	To learn more, refer to the `.refit_full` method docstring which explains how "_FULL" models differ from normal models.
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1_FULL ...
	1.02s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBM_BAG_L1_FULL ...
	1.97s	 = Training   runtime
Fitting model: RandomForestGini_BAG_L1_FULL | Skipping fit via cloning parent ...
	0.77s	 = Training   runtime
	0.19s	 = Validation runtime
Fitting model: RandomForestEntr_BAG_L1_FULL | Skipping fit via cloning parent ...
	0.77s	 = Training   runtime
	0.19s	 = Validation runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: CatBoost_BAG_L1_FULL ...
	0.97s	 = Training   runtime
Fitting model: ExtraTreesGini_BAG_L1_FULL | Skipping fit via cloning parent ...
	0.68s	 = Training   runtime
	0.19s	 = Validation runtime
Fitting model: ExtraTreesEntr_BAG_L1_FULL | Skipping fit via cloning parent ...
	0.66s	 = Training   runtime
	0.18s	 = Validation runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: NeuralNetFastAI_BAG_L1_FULL ...
	Stopping at the best epoch learned earlier - 5.
	0.68s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: XGBoost_BAG_L1_FULL ...
	0.39s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: NeuralNetTorch_BAG_L1_FULL ...
	1.33s	 = Training   runtime
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMLarge_BAG_L1_FULL ...
	23.81s	 = Training   runtime
Fitting model: WeightedEnsemble_L2_FULL | Skipping fit via cloning parent ...
	Ensemble Weights: {'LightGBMXT_BAG_L1': 1.0}
	0.16s	 = Training   runtime
Updated best model to "LightGBMXT_BAG_L1_FULL" (Previously "WeightedEnsemble_L2"). AutoGluon will default to using "LightGBMXT_BAG_L1_FULL" for predict() and predict_proba().
Refit complete, total runtime = 30.64s ... Best model: "LightGBMXT_BAG_L1_FULL"
Disabling decision threshold calibration for metric `accuracy` due to having fewer than 10000 rows of validation data for calibration, to avoid overfitting (2328 rows).
	`accuracy` is generally not improved through threshold calibration. Force calibration via specifying `calibrate_decision_threshold=True`.
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/home/mlioi/ufc-predictor-v2/models")

In [32]:
test_data = ufc_data.get_df_test()
test_data

,division,total_rounds,b_stance,r_momentum_ema,b_momentum_ema,BodySApM_career_dif,BodySApM_ema_dif,BodySLpM_career_dif,BodySLpM_ema_dif,ClinchSApM_career_dif,...,days_since_last_fight_dif,finish_rate_dif,height_dif,ko_per_fight_dif,reach_dif,reach_height_ratio_dif,sub_per_fight_dif,total_fights_dif,win_ratio_dif,label
336,welterweight,Five,Orthodox,0.427734,0.495117,-0.665042,-0.899259,-0.020014,0.371307,-0.197708,...,0.0,-0.208,7.62,-0.056,2.54,-0.030,0.000,1,0.133,0
2536,flyweight,Three,Orthodox,0.750000,0.250000,0.000500,0.106200,0.165000,0.115600,0.794500,...,112.0,0.500,20.32,0.000,15.24,-0.030,0.000,0,-0.500,0
2063,lightweight,Three,Orthodox,-0.023438,0.968750,0.208686,0.580281,0.439429,0.128147,0.119971,...,7.0,-0.400,7.62,-0.286,5.08,-0.018,0.000,-2,0.286,0
2382,middleweight,Three,Orthodox,-0.265625,0.672852,0.263278,0.740580,-0.550278,0.269725,0.977000,...,-63.0,-0.150,7.62,-0.300,-2.54,-0.057,0.100,4,-0.167,0
312,women,Five,Orthodox,0.375000,0.937500,-0.007333,0.017536,-0.017333,0.006336,0.096833,...,14.0,0.500,2.54,0.500,7.62,0.030,0.000,1,0.333,0
474,featherweight,Three,Orthodox,-0.673621,-0.843750,0.167080,0.228984,0.154400,0.053446,-0.067800,...,266.0,-0.500,0.00,-0.240,5.08,0.029,0.000,-20,-0.280,0
539,featherweight,Five,Orthodox,0.999245,-0.250977,-0.080350,-0.158723,-1.089925,-0.913892,-0.033062,...,0.0,-0.393,-10.16,-0.212,2.54,0.073,-0.118,-7,-0.024,0
729,lightweight,Three,Orthodox,-0.078125,-0.375000,-0.216833,-0.150275,0.144333,0.277132,0.119667,...,98.0,1.000,7.62,0.333,10.16,0.014,0.000,-3,-0.334,1
2825,middleweight,Three,Southpaw,-0.125000,0.246094,-1.086792,-1.273406,-1.653583,-1.615663,0.185125,...,196.0,-0.500,2.54,-0.667,5.08,0.012,0.375,5,0.083,0
717,heavyweight,Three,Orthodox,-0.007812,0.494995,0.279758,0.470093,-0.029967,0.145044,0.182264,...,-29.0,-0.100,-2.54,-0.022,-10.16,-0.039,-0.143,6,-0.088,1
2497,flyweight,Three,Southpaw,0.101562,-0.187500,0.247917,0.236861,-0.129083,-0.276530,-0.067917,...,182.0,0.667,-5.08,0.107,0.00,0.031,0.250,-3,0.071,0
1253,women,Three,Orthodox,-0.380127,-0.555664,-0.119778,0.265314,-0.298278,-0.653394,-0.446417,...,315.0,0.514,-2.54,0.200,2.54,0.030,0.033,-2,-0.083,0
1913,flyweight,Three,Southpaw,-0.263672,0.812500,-0.385444,-0.405374,-0.207917,-0.487347,-0.390083,...,472.0,-0.067,0.00,0.250,5.08,0.030,-0.222,-5,0.194,0
2018,light heavyweight,Three,Orthodox,0.625000,0.906250,0.764267,0.582840,-2.051867,-2.064629,0.300067,...,-35.0,0.000,-10.16,0.067,2.54,0.070,0.000,2,0.133,0
1075,welterweight,Three,Orthodox,-0.101562,-0.250000,-0.234571,-0.259478,0.091714,0.110886,-0.304143,...,-189.0,-1.000,-2.54,-0.429,2.54,0.029,-0.143,-5,-0.071,1
1281,welterweight,Three,Southpaw,0.108841,-0.154297,0.022035,0.140982,-0.309507,-0.240573,-0.307389,...,721.0,-0.200,2.54,-0.139,-2.54,-0.028,-0.077,-7,-0.181,0
2734,bantamweight,Three,Orthodox,0.875000,0.125000,0.570000,0.453000,0.111000,0.210600,0.000000,...,-126.0,-0.333,0.00,-0.333,0.00,0.000,0.000,0,-0.667,1
191,featherweight,Three,Orthodox,-0.755859,0.475037,0.158698,0.594107,0.282556,0.476686,-0.166024,...,126.0,0.089,0.00,-0.222,5.08,0.028,0.349,5,0.087,0
323,women,Five,Orthodox,-0.531250,0.687500,-0.119300,0.067949,-0.000750,0.522718,0.102950,...,76.0,0.334,2.54,0.300,5.08,0.014,0.000,-1,0.150,1
1998,flyweight,Three,Switch,0.750000,0.562500,-0.493750,-0.576304,-0.530500,-0.622472,-0.033250,...,168.0,0.000,0.00,0.250,2.54,0.015,-0.500,2,-0.500,0
703,welterweight,Three,Orthodox,-0.041016,-0.250000,0.195778,0.346847,0.029222,-0.035590,-0.244611,...,0.0,-0.667,-2.54,-0.444,0.00,0.014,0.000,-7,-0.167,0
1572,women,Three,Orthodox,-0.296875,-0.640015,-0.189346,0.932608,0.173038,0.917008,0.166885,...,-63.0,-0.133,5.08,0.077,5.08,0.000,-0.167,7,-0.115,0
1098,women,Three,Orthodox,0.750000,0.718750,-1.266100,-1.516112,-1.430000,-1.551168,-1.792800,...,-126.0,0.000,0.00,-0.800,-5.08,-0.031,0.600,3,-0.200,0
1996,middleweight,Three,Southpaw,-0.062500,0.750000,-0.072750,-0.079272,-1.140000,-1.032336,-0.045750,...,-315.0,-0.667,-2.54,-0.500,0.00,0.013,0.000,-2,0.250,1
2533,featherweight,Three,Southpaw,0.250000,-0.750000,-0.425500,-0.294400,0.015500,0.150400,0.755000,...,-56.0,-1.000,12.70,-0.500,10.16,-0.015,0.000,0,-0.500,1
1233,women,Three,Southpaw,-0.134766,0.375000,-0.272222,-0.210611,0.238333,0.404801,0.218556,...,189.0,0.500,-2.54,0.000,-2.54,-0.001,0.333,-6,0.000,0
2496,women,Three,Orthodox,-0.046875,-0.117706,0.196700,-0.004299,0.561900,1.279849,0.185800,...,581.0,-0.028,0.00,0.067,-2.54,-0.016,-0.100,9,-0.067,0
1878,middleweight,Three,Orthodox,-0.062500,0.187500,0.375750,0.430728,-0.153750,-0.471488,0.607500,...,322.0,-0.333,-15.24,-0.250,-17.78,-0.008,0.000,0,-0.250,0
397,featherweight,Five,Orthodox,0.498047,0.998489,0.130022,0.405205,1.173822,1.382486,0.030156,...,-154.0,0.365,10.16,0.153,-2.54,-0.073,0.125,7,-0.077,1
2741,heavyweight,Three,Orthodox,0.496094,0.466064,0.838274,1.215838,-0.119488,-0.168561,0.597952,...,-70.0,-0.107,0.00,0.000,-2.54,-0.013,-0.250,4,-0.208,0
477,middleweight,Three,Orthodox,-0.792969,0.656250,-0.216250,-0.091088,0.391575,0.377874,-0.141200,...,-55.0,0.000,17.78,0.150,12.70,-0.029,0.000,-3,0.225,1
2851,women,Three,Orthodox,-0.221444,0.927734,-0.611615,-0.969505,-0.526821,0.001595,-1.169147,...,-147.0,-0.243,15.24,-0.214,15.24,-0.001,0.115,-19,0.171,1
523,lightweight,Three,Orthodox,-0.331338,0.165921,-0.571333,-0.684055,0.083542,0.147931,-0.174958,...,-64.0,-0.472,-7.62,-0.166,-2.54,0.031,-0.125,0,-0.041,1
1694,women,Five,Orthodox,-0.257812,0.243164,-0.673986,-0.950090,0.329743,0.655689,-0.126357,...,-147.0,0.133,-5.08,0.100,-7.62,-0.015,-0.043,3,-0.114,0
2570,featherweight,Three,Orthodox,0.828125,0.111328,0.177111,0.039958,-0.118889,-0.280372,0.178222,...,105.0,-0.750,0.00,-0.556,-2.54,-0.014,0.000,3,-0.223,0
896,bantamweight,Three,Orthodox,-0.503906,0.739258,0.593157,0.162774,0.587443,0.546881,-0.329557,...,-118.0,0.047,-5.08,-0.300,0.00,0.029,0.300,2,-0.050,1
1324,women,Five,Orthodox,-0.548828,-0.088776,0.202349,-0.073524,0.278349,0.590106,-0.125786,...,-7.0,-0.114,0.00,0.133,5.08,0.032,-0.222,6,-0.089,0
2610,women,Three,Orthodox,0.692296,0.476562,-0.245217,-0.068237,-0.971540,-1.160055,-0.115435,...,7.0,-0.050,-5.08,-0.080,-7.62,-0.016,0.103,-18,0.234,1
2733,lightweight,Three,Orthodox,0.741943,0.561737,0.335400,0.949098,0.761600,1.002317,0.151033,...,154.0,0.100,-2.54,0.166,5.08,0.043,-0.200,3,-0.166,0
2722,flyweight,Three,Orthodox,-0.054688,-0.449326,-0.025875,-0.173585,-0.212652,-0.395525,0.676902,...,-91.0,0.500,-2.54,0.152,-7.62,-0.030,0.062,9,-0.071,0
2548,heavyweight,Three,Orthodox,-0.759231,-0.031250,1.397297,1.180526,0.474451,-0.150307,0.438682,...,28.0,-0.205,2.54,-0.231,0.00,-0.014,0.174,-34,0.236,1
2106,women,Three,Orthodox,-0.226562,0.625000,-0.088476,-0.044437,-0.535905,-0.754254,-0.172286,...,56.0,-0.333,-10.16,0.000,-15.24,-0.031,-0.143,-4,0.238,1
1445,heavyweight,Three,Orthodox,0.636840,0.750000,-0.329516,-0.397526,0.120597,0.182255,-0.286548,...,28.0,0.444,5.08,0.710,2.54,-0.014,-0.032,-29,0.419,1
816,flyweight,Three,Southpaw,0.437500,0.324219,-0.013750,-0.018043,-0.496875,0.097064,0.066500,...,-35.0,0.667,12.70,0.000,10.16,-0.017,0.250,4,-0.250,0
164,featherweight,Three,Orthodox,0.671570,0.789062,0.262357,0.226887,-0.458357,-0.914972,0.141429,...,350.0,0.550,-7.62,0.000,5.08,0.076,0.286,-7,-0.143,0
1407,heavyweight,Three,Southpaw,0.250000,0.250000,0.665500,0.703600,-1.169000,-1.029400,-0.100000,...,238.0,1.000,0.00,0.500,-2.54,-0.014,0.000,0,0.000,0
2683,bantamweight,Three,Switch,-0.598816,0.687500,-0.015167,0.013391,1.231500,1.170129,0.193833,...,63.0,-0.334,-5.08,0.107,-2.54,0.015,-0.143,-10,0.321,0
1533,featherweight,Three,Switch,-0.250000,-0.531250,-0.573400,-0.496152,-0.053000,-0.056149,-0.373600,...,-224.0,0.000,-10.16,0.000,-15.24,-0.025,0.000,3,0.100,0
1531,welterweight,Three,Orthodox,0.835898,0.906250,-0.246645,-0.164443,-0.256900,-0.106157,-0.225264,...,14.0,0.062,5.08,0.173,0.00,-0.028,-0.091,-17,0.073,1
92,lightweight,Three,Orthodox,-0.312500,-0.312500,0.643750,0.498232,0.107750,0.092912,0.196500,...,14.0,0.500,0.00,0.000,0.00,0.000,0.250,0,0.000,1
821,women,Three,Orthodox,0.750000,-0.250000,0.575500,0.460400,0.633500,0.786800,-0.367000,...,35.0,0.000,-2.54,0.000,7.62,0.062,0.000,0,-0.500,0
2248,welterweight,Three,Orthodox,0.937500,0.437500,-0.116500,0.094968,0.831000,0.640880,-0.045000,...,42.0,-0.083,7.62,-0.250,5.08,-0.016,0.000,0,-0.250,1
738,lightweight,Three,Orthodox,-0.750000,-0.625000,-1.020333,-1.251880,-0.387333,-0.412280,-1.157667,...,-41.0,1.000,0.00,0.333,2.54,0.014,0.000,1,0.333,0
334,heavyweight,Three,Orthodox,-0.043945,0.593018,-0.182491,-0.293726,-1.798673,-0.797689,-0.304727,...,175.0,0.190,-15.24,0.100,-20.32,-0.024,0.000,2,-0.017,0
1271,lightweight,Three,Orthodox,-0.570312,0.250000,0.467571,0.271185,-0.379643,-0.203311,-0.415286,...,-77.0,0.250,12.70,0.357,10.16,-0.016,-0.286,-5,-0.071,1
546,featherweight,Three,Southpaw,-0.046875,-0.281250,0.388667,0.224038,0.638667,0.648510,0.012833,...,77.0,0.167,-5.08,-0.167,0.00,0.030,0.233,-1,-0.067,1
75,women,Three,Orthodox,-0.062500,0.343750,-0.341000,-0.640416,-0.272050,-0.139328,-5.281450,...,-35.0,0.334,5.08,-0.250,7.62,0.015,0.400,1,-0.150,1
1239,women,Five,Orthodox,0.998901,0.375000,0.614436,0.282272,-0.505538,-0.449003,0.730436,...,-77.0,0.250,-5.08,-0.205,-2.54,0.015,0.179,-10,-0.256,0
787,lightweight,Five,Southpaw,0.999023,0.749023,0.195989,0.428502,0.526111,0.535562,0.408833,...,511.0,0.378,-2.54,0.500,10.16,0.072,-0.200,0,-0.100,0
2103,heavyweight,Five,Orthodox,0.999992,0.498047,-0.070050,-0.518293,0.504900,0.415301,-0.315094,...,-938.0,0.125,0.00,0.095,-7.62,-0.039,-0.016,-12,-0.063,0
2691,lightweight,Five,Orthodox,-0.250086,-0.406250,-0.447925,-0.423878,0.456594,0.239805,-0.038913,...,518.0,0.091,-5.08,0.275,-7.62,-0.013,-0.500,-27,-0.288,0
1915,women,Three,Southpaw,-0.387207,-0.023438,-0.055701,-0.437780,-0.107961,-0.442117,0.421156,...,-350.0,0.267,2.54,0.286,7.62,0.032,-0.039,-4,0.169,1
1838,flyweight,Three,Orthodox,0.218750,0.472656,0.189800,0.069008,-0.404625,-0.340512,0.438175,...,360.0,-0.267,-2.54,0.000,5.08,0.043,-0.150,3,0.025,0
725,featherweight,Three,Southpaw,-0.796967,-0.187500,-0.101150,0.013804,0.538367,0.036878,-0.050867,...,28.0,-0.333,15.24,-0.067,10.16,-0.028,-0.133,-11,-0.100,1
2398,middleweight,Five,Orthodox,-0.328690,0.875000,-0.105729,-0.275146,0.652521,-0.141349,-0.205250,...,-308.0,0.400,2.54,0.479,-5.08,-0.041,0.145,-13,0.375,0
1038,women,Three,Orthodox,-0.766602,0.500000,0.706000,0.567379,1.751700,2.079678,1.175700,...,-28.0,-0.167,12.70,0.000,12.70,0.001,-0.100,-8,-0.100,1
915,light heavyweight,Three,Southpaw,-0.531250,0.937500,-1.443400,-0.943606,0.984800,0.937227,-0.859350,...,21.0,0.083,5.08,0.100,5.08,-0.001,0.250,-1,0.400,1
2416,flyweight,Three,Orthodox,0.250000,-0.750000,-0.716500,-0.239800,0.199000,0.153000,0.548000,...,-91.0,-1.000,5.08,-0.500,22.86,0.107,0.000,0,-0.500,0
2710,flyweight,Three,Orthodox,0.239258,0.468750,0.684300,0.732133,1.297300,1.233093,-0.199700,...,-7.0,-0.083,-5.08,0.109,-5.08,0.000,-0.091,-6,0.255,1
12,welterweight,Three,Orthodox,0.720585,0.795898,-0.278088,-0.291334,1.201665,1.021797,-0.095494,...,29.0,0.381,7.62,0.033,5.08,-0.015,0.300,-8,0.200,0
379,middleweight,Three,Southpaw,-0.377953,0.903320,0.260253,0.385857,0.391141,0.604556,0.709900,...,-70.0,0.078,2.54,0.282,-7.62,-0.054,-0.194,-7,0.053,0
1974,middleweight,Three,Orthodox,0.750000,0.437500,0.696000,0.668792,-1.558000,-1.872584,-0.189000,...,-28.0,-0.333,0.00,-0.500,-12.70,-0.067,0.000,2,-0.250,1
689,welterweight,Three,Orthodox,-0.715338,-0.637756,-0.110286,-0.336396,0.950692,0.605937,0.210703,...,-308.0,-0.075,12.70,-0.173,15.24,0.012,0.161,-5,0.045,1
1696,light heavyweight,Three,Orthodox,0.609375,0.375000,-0.470167,0.188086,-0.043333,-0.015512,-0.767000,...,-14.0,-0.250,-5.08,0.000,-7.62,-0.013,-0.167,-3,0.000,1
2319,women,Three,Orthodox,-0.702148,-0.625000,2.433400,1.810560,0.706800,0.686441,1.126700,...,-658.0,0.000,-12.70,0.000,-15.24,-0.014,0.000,-7,0.033,1
905,bantamweight,Three,Orthodox,0.060059,0.562500,-0.034591,-0.203664,-0.334341,-0.257897,0.633295,...,154.0,-0.667,-2.54,-0.182,5.08,0.043,-0.182,-7,-0.045,1
1017,heavyweight,Three,Orthodox,-0.810558,-0.520996,0.849273,1.287173,0.016296,-0.745818,0.203953,...,49.0,0.166,2.54,-0.060,2.54,-0.001,0.145,-16,-0.011,0
203,heavyweight,Three,Orthodox,-0.009277,-0.316589,0.505629,0.507246,-0.061280,-0.446133,0.727175,...,-56.0,0.139,5.08,0.136,5.08,0.000,-0.111,3,-0.084,0
361,flyweight,Five,Southpaw,0.999481,0.855469,-0.229429,-0.110305,-0.970143,-0.973870,-0.465536,...,-70.0,-0.052,2.54,-0.133,-2.54,-0.032,0.050,-7,-0.117,0
648,women,Three,Orthodox,-0.562500,-0.304688,-0.075286,-0.201304,-0.749000,-0.846019,-0.114429,...,0.0,-0.333,10.16,0.143,12.70,0.016,-0.357,3,-0.071,0
338,heavyweight,Three,Orthodox,0.250000,0.625000,0.045333,0.001800,-0.405833,-0.490360,0.084000,...,-105.0,0.000,-2.54,-0.500,-10.16,-0.040,0.667,1,0.167,0
2524,women,Three,Orthodox,-0.902588,-0.820801,-0.009517,-0.202004,-1.063833,-0.470021,0.485917,...,133.0,0.400,2.54,0.008,-2.54,-0.030,0.190,-1,0.038,1
385,middleweight,Three,Orthodox,0.960938,-0.187500,-0.331286,-0.296589,-0.225750,-0.004786,-0.167464,...,2088.0,-0.167,0.00,-0.143,2.54,0.013,0.000,-3,-0.357,1
646,bantamweight,Three,Orthodox,-0.625000,-0.375000,-0.058333,0.092840,0.295333,0.431640,1.367333,...,238.0,0.000,5.08,0.000,15.24,0.059,0.000,0,0.000,0
1152,lightweight,Three,Southpaw,0.463135,0.812500,0.075750,0.214210,-0.267750,-0.055022,-0.548250,...,-35.0,-0.238,5.08,0.000,5.08,0.000,-0.083,-8,0.167,0
1283,women,Three,Orthodox,0.139648,0.125000,-0.191333,0.053222,-0.093556,0.014830,-2.454111,...,-49.0,-0.200,5.08,-0.100,5.08,0.000,0.000,-7,-0.167,1
1605,light heavyweight,Three,Orthodox,0.281250,-0.538574,0.282636,0.257793,-0.069591,-0.079345,0.943205,...,-42.0,0.100,-7.62,-0.018,-5.08,0.015,0.091,6,0.055,0
2556,women,Three,Southpaw,0.750000,-0.656250,-0.850200,-1.178013,-1.309300,-1.914136,-0.743900,...,448.0,0.500,0.00,-0.500,2.54,0.015,0.400,3,-0.600,0
1422,women,Three,Orthodox,-0.280029,-0.299316,0.544083,0.271318,0.541311,0.574934,0.170871,...,-49.0,0.133,0.00,0.008,-2.54,-0.015,0.091,-1,0.128,1
65,welterweight,Three,Southpaw,0.250000,-0.156250,0.162000,0.240090,0.547500,0.641293,-0.826900,...,-147.0,0.667,12.70,0.400,10.16,-0.016,0.000,3,0.100,1
1823,heavyweight,Three,Orthodox,0.852303,0.333008,0.419186,-0.261438,0.349914,-0.141715,0.063043,...,28.0,-0.076,0.00,-0.157,2.54,0.013,0.071,-25,-0.100,0
2212,welterweight,Three,Orthodox,-0.036285,-0.210938,0.308762,0.108421,-0.199600,-0.124149,0.121333,...,91.0,-0.167,-7.62,-0.133,-15.24,-0.040,-0.057,-8,-0.238,0
2498,lightweight,Three,Orthodox,0.589844,0.250000,0.106250,0.159091,-0.150250,-0.515928,-0.047750,...,98.0,-1.000,0.00,-0.375,-10.16,-0.057,-0.250,-6,-0.125,1
2891,light heavyweight,Five,Southpaw,-0.517578,-0.025604,-0.654867,-0.359149,-0.738756,-0.424709,-0.089178,...,105.0,0.111,-7.62,0.023,-7.62,0.002,0.000,6,-0.067,1
2108,women,Three,Southpaw,-0.402344,-0.079590,0.244943,-0.460521,-0.601557,-0.661301,0.517784,...,70.0,-0.333,-2.54,0.000,0.00,0.016,-0.125,3,0.261,0
1678,featherweight,Three,Orthodox,-0.533203,0.468750,0.460889,0.223548,0.106611,-0.275648,0.701222,...,-63.0,0.250,-2.54,0.178,-12.70,-0.056,0.089,-4,0.133,0
1795,bantamweight,Three,Orthodox,0.851562,0.812500,0.557850,0.328651,-0.407200,-0.368480,0.139150,...,-7.0,0.800,-5.08,0.607,7.62,0.074,0.000,-3,0.036,0
2574,featherweight,Three,Orthodox,-0.079102,-0.355957,-0.003000,0.353105,-0.095283,-0.189379,-0.039162,...,140.0,0.571,2.54,0.091,0.00,-0.015,0.064,1,-0.245,0
1926,lightweight,Three,Southpaw,0.750000,0.687500,0.150500,0.246160,0.191000,0.013024,-0.584750,...,-28.0,-0.333,-2.54,-0.250,-5.08,-0.014,-0.250,2,-0.250,0
2337,featherweight,Three,Orthodox,0.250000,0.484375,0.644333,0.206058,0.068833,0.005935,-0.085833,...,49.0,-0.600,-7.62,0.000,-5.08,0.015,-0.167,4,0.333,0
1207,heavyweight,Three,Orthodox,0.214355,-0.156540,-1.112455,-2.347259,-0.743636,-1.301479,-0.602835,...,672.0,-0.364,5.08,0.159,-7.62,-0.068,-0.357,5,0.052,0
1818,featherweight,Three,Switch,0.334473,0.351562,-0.262422,0.073665,0.328111,0.323113,-0.085933,...,-217.0,0.167,0.00,0.195,-5.08,-0.029,-0.091,-4,0.065,1
2808,featherweight,Three,Orthodox,0.371094,-0.023438,-0.192232,0.293796,-0.173107,-0.298496,0.219929,...,14.0,0.500,0.00,0.429,5.08,0.030,-0.089,-1,-0.036,0
1455,lightweight,Three,Southpaw,0.980469,0.865784,0.656929,0.894652,0.304286,0.225274,0.405589,...,-249.0,0.238,-5.08,0.232,0.00,0.029,-0.179,6,-0.232,0
1884,middleweight,Three,Orthodox,0.750000,0.437500,-1.863000,-1.970344,-1.929000,-1.732704,-0.006250,...,140.0,0.000,5.08,-1.000,-5.08,-0.057,0.750,2,-0.250,0
1154,women,Three,Orthodox,-0.360352,0.239746,0.197136,-0.169943,0.001118,0.243898,0.569582,...,-14.0,-0.114,-2.54,-0.200,-5.08,-0.015,0.182,1,0.136,0
1151,women,Three,Southpaw,0.250000,0.453125,-0.086333,-0.221335,-1.801333,-1.621508,0.099000,...,-56.0,0.000,-5.08,0.000,-7.62,-0.014,0.000,4,0.167,0
233,light heavyweight,Three,Orthodox,-0.282227,-0.265625,0.256633,0.263838,-0.012467,-0.147944,0.706600,...,231.0,0.036,-5.08,0.100,-2.54,0.015,-0.100,-4,-0.033,1
2677,welterweight,Three,Orthodox,-0.062500,-0.596802,0.287250,0.804855,-0.752308,-0.752234,0.080865,...,-21.0,-0.571,-2.54,-0.019,2.54,0.028,-0.500,9,-0.212,0
1146,bantamweight,Three,Orthodox,0.726562,-0.125000,0.777143,0.328944,0.198619,0.063535,-0.288286,...,35.0,-0.600,-7.62,0.000,-2.54,0.033,-0.429,-4,-0.047,0
2184,heavyweight,Three,Orthodox,0.554108,0.375000,0.209667,0.093904,0.023000,0.123911,0.069133,...,14.0,-0.056,10.16,-0.200,17.78,0.038,0.200,-12,0.067,1
1686,featherweight,Five,Orthodox,0.187494,0.748047,-0.165710,-0.093310,-0.643662,-1.656687,-0.055734,...,456.0,-0.236,0.00,-0.042,5.08,0.028,-0.083,-15,0.139,0
1523,featherweight,Three,Switch,-0.132812,0.250000,-0.132071,-0.118087,0.831500,0.901023,0.041286,...,-136.0,-0.400,7.62,-0.143,2.54,-0.029,-0.143,-5,-0.214,0
1634,light heavyweight,Five,Orthodox,-0.758184,0.234375,-0.203524,-0.452159,-0.879286,-0.702661,0.729833,...,168.0,0.154,10.16,0.143,15.24,0.024,0.000,-15,0.048,0
1015,women,Five,Orthodox,0.921875,0.875000,1.545500,1.397749,0.064000,-0.238152,1.855667,...,-189.0,0.267,-7.62,0.334,-12.70,-0.029,0.000,-3,0.167,0
236,middleweight,Three,Orthodox,-0.268356,0.708984,0.039067,-0.058609,0.168244,0.158016,-0.192200,...,-56.0,-0.500,5.08,-0.278,5.08,-0.001,0.049,-7,0.105,1
2729,women,Five,Orthodox,0.171326,-0.328613,-0.356610,0.153936,0.425487,0.374306,-0.255753,...,133.0,-0.015,-2.54,0.091,7.62,0.064,-0.104,-3,-0.007,0
2231,lightweight,Three,Orthodox,-0.201294,-0.046875,-0.005321,-0.505851,-0.007692,0.375413,-0.197769,...,280.0,0.714,12.70,0.179,10.16,-0.016,0.333,-7,0.129,1
992,lightweight,Three,Southpaw,0.431549,0.375000,-0.236267,-0.952270,-0.009533,-0.224684,-0.777867,...,-1582.0,0.000,12.70,-0.133,17.78,0.029,0.133,-12,0.000,1
235,heavyweight,Three,Southpaw,0.310280,0.796875,0.271153,0.277080,0.055918,-1.295514,0.433765,...,-66.0,-0.318,-27.94,0.039,-25.40,0.016,-0.235,-11,0.020,0
31,welterweight,Five,Orthodox,0.373993,0.960938,-0.093600,-0.378294,0.721886,0.585454,0.017733,...,-120.0,0.250,7.62,0.238,15.24,0.042,0.000,-8,0.057,1
1845,women,Three,Orthodox,0.839539,0.484375,-0.588976,-0.730950,-0.078190,-0.529156,-0.174048,...,77.0,0.400,-15.24,0.000,-5.08,0.062,0.333,-8,0.119,0
2642,light heavyweight,Five,Southpaw,0.935547,0.948792,-0.161159,0.477955,-1.108230,-0.391884,0.045294,...,203.0,0.028,-7.62,-0.167,-7.62,0.002,0.000,5,-0.246,0
940,bantamweight,Three,Orthodox,0.250000,0.281250,0.464300,0.706061,0.051500,0.507405,0.165500,...,63.0,-0.500,-2.54,0.200,-12.70,-0.057,-0.500,3,-0.100,0
1477,bantamweight,Three,Southpaw,-0.031250,-0.814453,0.039800,0.177930,-0.870267,-0.862307,0.384444,...,-63.0,0.300,-10.16,0.044,-5.08,0.031,0.000,4,-0.244,0
1956,light heavyweight,Three,Orthodox,0.179688,-0.750000,-0.212929,-0.104676,-0.434500,-0.650582,-0.435571,...,126.0,-1.000,-2.54,-0.286,-10.16,-0.039,-0.286,-5,-0.571,0

In [33]:
predictor.evaluate(test_data)

{'accuracy': 0.5986277873070326,
 'balanced_accuracy': 0.5782699665231946,
 'mcc': 0.16545215899635737,
 'roc_auc': 0.642431850789096,
 'f1': 0.47533632286995514,
 'precision': 0.5549738219895288,
 'recall': 0.41568627450980394}

In [34]:
pd.set_option('display.max_rows', None)
predictor.feature_importance(test_data)

Computing feature importance via permutation shuffling for 72 features using 583 rows with 5 shuffle sets...
	3.96s	= Expected runtime (0.79s per shuffle set)
	0.88s	= Actual runtime (Completed 5 of 5 shuffle sets)

,importance,stddev,p_value,n,p99_high,p99_low
age_dif,5.145798e-03,0.015999,0.255898,5,0.038088,-0.027796
sub_per_fight_dif,4.116638e-03,0.003116,0.020897,5,0.010532,-0.002299
GroundSApM_career_dif,3.773585e-03,0.003068,0.025687,5,0.010091,-0.002544
BodySApM_ema_dif,2.744425e-03,0.004305,0.113588,5,0.011609,-0.006120
TSApM_ema_dif,2.744425e-03,0.008280,0.249867,5,0.019792,-0.014303
DistSApM_career_dif,2.744425e-03,0.003758,0.088904,5,0.010482,-0.004993
ClinchSLpM_ema_dif,2.401372e-03,0.004634,0.155530,5,0.011944,-0.007141
SLpM_ema_dif,2.058319e-03,0.002236,0.054350,5,0.006663,-0.002547
avg_time_career_dif,2.058319e-03,0.002818,0.088904,5,0.007862,-0.003745
CtrlpM_career_dif,1.715266e-03,0.002101,0.070964,5,0.006041,-0.002610
TStr_Def_ema_dif,1.372213e-03,0.000767,0.008065,5,0.002952,-0.000207
reach_dif,1.372213e-03,0.002818,0.168751,5,0.007175,-0.004431
DistSLpM_ema_dif,1.372213e-03,0.001879,0.088904,5,0.005241,-0.002497
TD_Acc_career_dif,1.029160e-03,0.002601,0.213159,5,0.006385,-0.004327
ClinchSApM_career_dif,6.861063e-04,0.004131,0.364591,5,0.009192,-0.007819
current_win_streak_dif,3.430532e-04,0.002818,0.399483,5,0.006146,-0.005460
b_stance,3.430532e-04,0.002236,0.374434,5,0.004948,-0.004262
current_lose_streak_dif,0.000000e+00,0.000000,0.500000,5,0.000000,0.000000
r_momentum_ema,-2.220446e-17,0.004697,0.500000,5,0.009672,-0.009672
days_since_debut_dif,-3.430532e-04,0.005342,0.553617,5,0.010657,-0.011343
Str_Acc_ema_dif,-3.430532e-04,0.003299,0.586218,5,0.006450,-0.007137
TD_Acc_ema_dif,-3.430532e-04,0.005342,0.553617,5,0.010657,-0.011343
TSLpM_ema_dif,-6.861063e-04,0.001956,0.761690,5,0.003341,-0.004713
TStr_Acc_ema_dif,-6.861063e-04,0.003557,0.655771,5,0.006637,-0.008010
finish_rate_dif,-6.861063e-04,0.004473,0.625566,5,0.008524,-0.009896
HeadSLpM_ema_dif,-6.861063e-04,0.002301,0.729265,5,0.004052,-0.005424
SApM_ema_dif,-6.861063e-04,0.006137,0.592549,5,0.011949,-0.013322
TStr_Acc_career_dif,-1.029160e-03,0.002870,0.766198,5,0.004881,-0.006939
HeadSLpM_career_dif,-1.372213e-03,0.002544,0.852872,5,0.003866,-0.006611
BodySLpM_ema_dif,-1.372213e-03,0.002544,0.852872,5,0.003866,-0.006611
ClinchSApM_ema_dif,-1.372213e-03,0.003299,0.797488,5,0.005421,-0.008166
SLpM_career_dif,-1.715266e-03,0.001213,0.982945,5,0.000782,-0.004213
Str_Def_career_dif,-2.058319e-03,0.001435,0.983661,5,0.000897,-0.005013
TSApM_career_dif,-2.058319e-03,0.002236,0.945650,5,0.002547,-0.006663
ko_per_fight_dif,-2.058319e-03,0.003068,0.896000,5,0.004259,-0.008376
LegSApM_career_dif,-2.401372e-03,0.004305,0.859822,5,0.006463,-0.011266
reach_height_ratio_dif,-2.401372e-03,0.002601,0.946031,5,0.002955,-0.007758
win_ratio_dif,-2.401372e-03,0.003949,0.877254,5,0.005729,-0.010532
b_momentum_ema,-2.401372e-03,0.004634,0.844470,5,0.007141,-0.011944
BodySApM_career_dif,-2.401372e-03,0.001956,0.974197,5,0.001625,-0.006428
DistSLpM_career_dif,-2.744425e-03,0.004131,0.894211,5,0.005761,-0.011250
TSLpM_career_dif,-2.744425e-03,0.003116,0.939878,5,0.003671,-0.009160
TStr_Def_career_dif,-2.744425e-03,0.004305,0.886412,5,0.006120,-0.011609
total_rounds,-3.087479e-03,0.001879,0.989344,5,0.000781,-0.006956
GroundSLpM_career_dif,-3.087479e-03,0.002236,0.981659,5,0.001517,-0.007692
SApM_career_dif,-3.087479e-03,0.002236,0.981659,5,0.001517,-0.007692
GroundSApM_ema_dif,-3.087479e-03,0.004095,0.916448,5,0.005344,-0.011519
Sub_Avg_ema_dif,-3.430532e-03,0.006861,0.836918,5,0.010696,-0.017558
HeadSApM_ema_dif,-3.773585e-03,0.004603,0.929659,5,0.005703,-0.013250
LegSLpM_career_dif,-3.773585e-03,0.003299,0.968596,5,0.003020,-0.010567
Str_Acc_career_dif,-3.773585e-03,0.002818,0.979907,5,0.002030,-0.009577
total_fights_dif,-4.116638e-03,0.001956,0.995369,5,-0.000090,-0.008143
DistSApM_ema_dif,-4.116638e-03,0.006016,0.899643,5,0.008270,-0.016503
days_since_last_fight_dif,-4.116638e-03,0.002601,0.987978,5,0.001240,-0.009473
BodySLpM_career_dif,-4.459691e-03,0.003949,0.967507,5,0.003671,-0.012590
GroundSLpM_ema_dif,-4.459691e-03,0.004473,0.955169,5,0.004750,-0.013669
TD_Def_career_dif,-5.145798e-03,0.003431,0.985770,5,0.001918,-0.012209
TD_Avg_ema_dif,-5.145798e-03,0.004538,0.967855,5,0.004198,-0.014490
CtrlpM_ema_dif,-5.488851e-03,0.002818,0.993944,5,0.000314,-0.011292
height_dif,-5.831904e-03,0.005370,0.963954,5,0.005224,-0.016888
TD_Avg_career_dif,-6.174957e-03,0.001956,0.998939,5,-0.002148,-0.010202
LegSLpM_ema_dif,-6.518010e-03,0.004095,0.988197,5,0.001914,-0.014950
HeadSApM_career_dif,-6.518010e-03,0.002236,0.998569,5,-0.001913,-0.011123
TD_Def_ema_dif,-6.861063e-03,0.005287,0.977983,5,0.004025,-0.017747
avg_time_ema_dif,-6.861063e-03,0.005001,0.981315,5,0.003436,-0.017158
OpCtrlpM_career_dif,-7.204117e-03,0.005342,0.980330,5,0.003795,-0.018204
ClinchSLpM_career_dif,-7.890223e-03,0.002601,0.998766,5,-0.002534,-0.013246
OpCtrlpM_ema_dif,-8.233276e-03,0.006349,0.977936,5,0.004839,-0.021306
Sub_Avg_career_dif,-8.233276e-03,0.003719,0.996122,5,-0.000577,-0.015890
Str_Def_ema_dif,-8.233276e-03,0.002544,0.999032,5,-0.002995,-0.013472
LegSApM_ema_dif,-1.132075e-02,0.003557,0.998970,5,-0.003997,-0.018644
division,-1.440823e-02,0.002601,0.999878,5,-0.009052,-0.019764

<div style="text-align: center;">
     <img src="../img/ufc_logo.png" width="800" /> 
</div>