# 🔹 UFC Fight Predictor v2 Model Training

<div style="text-align: center;">
  🔹 <img src="../img/ufc_logo.png" width="50" /> 🔹
</div>

#  Import Libraries and Setup Environment

In [1]:
# Import necessary libraries
import os
import sys
import pandas as pd
import logging
from autogluon.tabular import TabularDataset, TabularPredictor
pd.set_option('display.max_colwidth', 200) 

# Get the current working directory
current_dir = os.getcwd()

# Navigate to the project root
project_root = os.path.abspath(os.path.join(current_dir, '..'))

# Import from /src
sys.path.append(os.path.join(project_root))
from src.helpers import prepare_modeling_df

logging.basicConfig(level=logging.INFO, format='[%(levelname)s] %(message)s')
logger = logging.getLogger(__name__)

<div style="text-align: center;">
  🔹 <img src="../img/ufc_logo.png" width="50" /> 🔹
</div>

#  Load Data

In [2]:
# Define the path to the CSV file
file_path = os.path.join(project_root, 'data', 'processed', 'ufc_fte.csv')

# Load the CSV into a DataFrame
try:
    ufc_df = pd.read_csv(file_path)
    logger.info(f"✅ Data successfully loaded: {ufc_df.shape[0]} rows, {ufc_df.shape[1]} columns.")
except Exception as e:
    logger.error(f"❌ Error loading data: {e}")

[INFO] ✅ Data successfully loaded: 4363 rows, 199 columns.

# ⚙️ Calibration

In [3]:
ufc_data = prepare_modeling_df(
    ufc_df,
    start_date="2008-01-01",
    drop_r=True, drop_b=True,
    keep_last=False, keep_career=True, keep_ema=True,
    compute_dif=True,
    drop_cols=['title_fight', 'date', 'b_momentum', 'r_momentum'],
    keep_cols=['b_stance','b_momentum_ema', 'r_momentum_ema'],
    min_total_fights=3,
    as_ufcdata=True,
    skip_diff_bases=["momentum_ema"]
)

[INFO] Filtered by min_total_fights=3: 4220 → 3342 rows

In [4]:
ufc_data

📊 UFC Dataset Summary
----------------------------------------
🧪 Total samples       : 3342
🧪 Train/Test split    : 2673 / 669
🧪 Total features      : 72

🔢 Numerical features  : 69
🔠 Categorical features: 3
    - Binary           : 1
    - Multiclass       : 2

🔠 Categorical feature names (all):
      b_stance, division, total_rounds

   • Binary categorical features:
      total_rounds

   • Multiclass categorical features:
      b_stance, division

🏷 Label distribution (raw):
   - Class 0: 1967 (58.9%)
   - Class 1: 1375 (41.1%)

✅ No missing values detected

📈 Feature summary statistics (train set):
                              mean       std       min       max
r_momentum_ema               0.190     0.561    -0.984     1.000
b_momentum_ema               0.284     0.539    -0.949     1.000
BodySApM_career_dif          0.023     0.434    -2.139     2.311
BodySApM_ema_dif            -0.006     0.564    -3.920     3.409
BodySLpM_career_dif          0.009     0.608    -3.910     4.469
BodySLpM_ema_dif            -0.000     0.690    -5.678     3.324
ClinchSApM_career_dif        0.019     0.525    -6.235     5.997
ClinchSApM_ema_dif           0.002     0.692   -11.550     6.391
ClinchSLpM_career_dif        0.003     0.730    -6.026     5.807
ClinchSLpM_ema_dif           0.022     0.811    -6.900    10.851
CtrlpM_career_dif           -0.096    11.249   -41.104    53.992
CtrlpM_ema_dif               0.510    12.248   -42.579    56.363
DistSApM_career_dif          0.053     1.486    -7.720     8.723
DistSApM_ema_dif            -0.084     1.820    -9.202    10.548
DistSLpM_career_dif          0.055     1.649    -6.702     7.793
DistSLpM_ema_dif             0.041     1.938   -10.958     9.277
GroundSApM_career_dif        0.007     0.742    -4.841     7.354
GroundSApM_ema_dif          -0.022     1.035    -6.616    11.259
GroundSLpM_career_dif        0.019     1.397   -10.089    14.248
GroundSLpM_ema_dif           0.079     1.541   -16.040    16.281
HeadSApM_career_dif          0.044     1.478    -8.476     9.473
HeadSApM_ema_dif            -0.092     1.953   -11.002    13.945
HeadSLpM_career_dif          0.069     2.089   -12.824    17.047
HeadSLpM_ema_dif             0.142     2.331   -17.773    18.908
LegSApM_career_dif           0.012     0.437    -1.877     2.267
LegSApM_ema_dif             -0.006     0.531    -2.840     3.186
LegSLpM_career_dif          -0.002     0.582    -2.825     3.104
LegSLpM_ema_dif              0.000     0.680    -3.590     3.817
OpCtrlpM_career_dif          0.598     8.609   -32.604    30.338
OpCtrlpM_ema_dif             0.517     9.857   -32.740    36.503
SApM_career_dif              0.079     1.794    -8.487     9.052
SApM_ema_dif                -0.104     2.332   -16.239    14.550
SLpM_career_dif              0.076     2.401   -14.405    16.914
SLpM_ema_dif                 0.142     2.670   -17.015    17.347
Str_Acc_career_dif          -0.024    10.954   -42.173    42.320
Str_Acc_ema_dif              0.471    12.513   -55.963    43.554
Str_Def_career_dif          -0.366    10.553   -58.058    36.840
Str_Def_ema_dif              0.535    12.313   -55.777    39.357
Sub_Avg_career_dif           0.055     2.029   -14.301    16.420
Sub_Avg_ema_dif              0.116     2.153   -26.472    22.578
TD_Acc_career_dif           -0.713    23.961   -83.333    83.974
TD_Acc_ema_dif               0.582    27.851   -86.487    88.088
TD_Avg_career_dif           -0.038     2.074   -13.181     9.730
TD_Avg_ema_dif               0.087     2.249   -14.253    17.149
TD_Def_career_dif           -0.265    27.192   -83.482    91.667
TD_Def_ema_dif               0.235    32.840   -94.816    95.956
TSApM_career_dif             0.112     1.983    -7.803    11.357
TSApM_ema_dif               -0.097     2.582   -15.790    17.716
TSLpM_career_dif             0.092     2.899   -19.656    19.954
TSLpM_ema_dif                0.207     3.173   -19.008    22.991
TStr_Acc_career_dif          0.103    11.895   -43.263    44.159
TStr_Acc_ema_dif             0.669    13.726   -52.548    43.967
TStr_Def_career_dif         -0.299    12.084   -54.994    44.324
TStr_Def_ema_dif             0.358    13.680   -54.164    46.097
age_dif                     -0.724     5.294   -17.000    16.000
avg_time_career_dif         -0.341     3.709   -14.528    11.283
avg_time_ema_dif            -0.688     4.925   -19.905    15.231
current_lose_streak_dif     -0.165     0.999    -6.000     5.000
current_win_streak_dif       0.065     2.461   -18.000    10.000
days_since_debut_dif      -378.074  1399.203 -7792.000  4943.000
days_since_last_fight_dif    4.368   269.615 -2810.000  4047.000
finish_rate_dif              0.002     0.377    -1.000     1.000
height_dif                   0.101     6.323   -33.020    30.480
ko_per_fight_dif            -0.002     0.240    -0.857     1.000
reach_dif                   -0.251     8.205   -30.480    27.940
reach_height_ratio_dif      -0.002     0.036    -0.127     0.136
sub_per_fight_dif           -0.004     0.225    -1.000     1.000
total_fights_dif            -2.273     7.337   -34.000    26.000
win_ratio_dif               -0.014     0.206    -0.750     0.833

⚙️ Preprocessing status:
   - Standardized?     : ❌
   - Correlation cached (raw)      : ❌
   - Correlation cached (processed): ❌
----------------------------------------

<div style="text-align: center;">
  🔹 <img src="../img/ufc_logo.png" width="50" /> 🔹
</div>

# 🔹 UFC Machine Learning Training

### 🚀 AutoGluon Training

In [5]:
train_data = ufc_data.get_df_train()
train_data

,division,total_rounds,b_stance,r_momentum_ema,b_momentum_ema,BodySApM_career_dif,BodySApM_ema_dif,BodySLpM_career_dif,BodySLpM_ema_dif,ClinchSApM_career_dif,...,days_since_last_fight_dif,finish_rate_dif,height_dif,ko_per_fight_dif,reach_dif,reach_height_ratio_dif,sub_per_fight_dif,total_fights_dif,win_ratio_dif,label
566,heavyweight,Three,Orthodox,-0.343750,-0.396545,0.184129,0.039812,0.279729,0.233094,0.369214,...,168.0,0.125,-2.54,0.086,0.00,0.014,0.071,9,0.171,0
1674,welterweight,Three,Orthodox,-0.697999,-0.343750,-0.042783,-0.001345,0.041809,-0.101336,-0.099270,...,70.0,-0.143,5.08,-0.133,15.24,0.056,-0.042,-19,-0.183,0
1493,flyweight,Three,Orthodox,-0.536133,0.552490,0.064183,-0.266999,0.550033,0.393712,0.079617,...,-28.0,0.381,5.08,0.167,2.54,-0.016,0.050,2,-0.017,1
2814,middleweight,Three,Southpaw,-0.562500,-0.149414,0.444050,0.411227,-1.399000,-0.947351,-0.596250,...,-35.0,-0.167,-7.62,0.000,-15.24,-0.039,0.000,6,0.100,1
3275,flyweight,Three,Orthodox,-0.828979,-0.406250,0.592046,0.210559,0.082308,0.256021,-0.017123,...,84.0,0.500,-2.54,0.000,-5.08,-0.014,0.169,-8,-0.062,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1882,middleweight,Three,Orthodox,-0.125000,0.825684,-0.295667,-0.409769,-0.074633,-0.218281,0.334100,...,-21.0,0.286,2.54,0.182,2.54,0.000,0.000,8,-0.031,1
698,welterweight,Three,Orthodox,0.281250,0.437500,0.371350,0.404360,0.253900,0.378102,-0.161050,...,36.0,-0.667,10.16,0.000,10.16,-0.003,-0.150,-1,0.350,0
2314,lightweight,Three,Orthodox,-0.085938,0.812500,-0.651679,-0.817328,0.177500,0.110203,-0.428143,...,266.0,0.750,15.24,0.250,17.78,0.013,0.357,-3,0.179,1
1708,welterweight,Three,Switch,0.981445,0.421387,0.331700,-0.160893,-0.251100,-0.415578,0.244200,...,-168.0,0.500,-7.62,-0.200,-5.08,0.014,0.536,1,-0.073,0
1283,bantamweight,Three,Orthodox,-0.266602,0.586914,0.043200,-0.569584,-0.452900,-0.680955,-0.329400,...,-77.0,0.086,10.16,-0.100,7.62,-0.018,0.000,0,-0.200,0

In [6]:
predictor = TabularPredictor(label='label', path = '../models').fit(train_data, presets='good')

Warning: path already exists! This predictor may overwrite an existing predictor! path="../models"
Preset alias specified: 'good' maps to 'good_quality'.
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.3.1
Python Version:     3.10.13
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP PREEMPT_DYNAMIC Sat Aug  2 11:37:34 UTC 2025
CPU Count:          24
Memory Avail:       8.61 GB / 15.51 GB (55.5%)
Disk Space Avail:   183.05 GB / 236.89 GB (77.3%)
===================================================
Presets specified: ['good']
Setting dynamic_stacking from 'auto' to True. Reason: Enable dynamic_stacking when use_bag_holdout is disabled. (use_bag_holdout=False)
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=8, num_bag_sets=1
Note: `save_bag_folds=False`! This will greatly reduce peak disk usage during fit (by ~8x), but runs the risk of an out-of-memory error during model refit if memory is small relative to the data size.
	You can avoid this risk by setting `save_bag_folds=True`.
DyStack is enabled (dynamic_stacking=True). AutoGluon will try to determine whether the input data is affected by stacked overfitting and enable or disable stacking as a consequence.
	This is used to identify the optimal `num_stack_levels` value. Copies of AutoGluon will be fit on subsets of the data. Then holdout validation data is used to detect stacked overfitting.
	Running DyStack for up to 900s of the 3600s of remaining time (25%).
	Running DyStack sub-fit in a ray process to avoid memory leakage. Enabling ray logging (enable_ray_logging=True). Specify `ds_args={'enable_ray_logging': False}` if you experience logging issues.
2025-08-21 21:43:03,122	INFO worker.py:1762 -- Started a local Ray instance. View the dashboard at 127.0.0.1:8265
		Context path: "/home/mlioi/ufc-predictor-v2/models/ds_sub_fit/sub_fit_ho"
(_dystack pid=133158) Running DyStack sub-fit ...
(_dystack pid=133158) Beginning AutoGluon training ... Time limit = 896s
(_dystack pid=133158) AutoGluon will save models to "/home/mlioi/ufc-predictor-v2/models/ds_sub_fit/sub_fit_ho"
(_dystack pid=133158) Train Data Rows:    2376
(_dystack pid=133158) Train Data Columns: 72
(_dystack pid=133158) Label Column:       label
(_dystack pid=133158) Problem Type:       binary
(_dystack pid=133158) Preprocessing data ...
(_dystack pid=133158) Selected class <--> label mapping:  class 1 = 1, class 0 = 0
(_dystack pid=133158) Using Feature Generators to preprocess the data ...
(_dystack pid=133158) Fitting AutoMLPipelineFeatureGenerator...
(_dystack pid=133158) 	Available Memory:                    8001.93 MB
(_dystack pid=133158) 	Train Data (Original)  Memory Usage: 1.69 MB (0.0% of available memory)
(_dystack pid=133158) 	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
(_dystack pid=133158) 	Stage 1 Generators:
(_dystack pid=133158) 		Fitting AsTypeFeatureGenerator...
(_dystack pid=133158) 			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
(_dystack pid=133158) 	Stage 2 Generators:
(_dystack pid=133158) 		Fitting FillNaFeatureGenerator...
(_dystack pid=133158) 	Stage 3 Generators:
(_dystack pid=133158) 		Fitting IdentityFeatureGenerator...
(_dystack pid=133158) 		Fitting CategoryFeatureGenerator...
(_dystack pid=133158) 			Fitting CategoryMemoryMinimizeFeatureGenerator...
(_dystack pid=133158) 	Stage 4 Generators:
(_dystack pid=133158) 		Fitting DropUniqueFeatureGenerator...
(_dystack pid=133158) 	Stage 5 Generators:
(_dystack pid=133158) 		Fitting DropDuplicatesFeatureGenerator...
(_dystack pid=133158) 	Types of features in original data (raw dtype, special dtypes):
(_dystack pid=133158) 		('float', [])  : 66 | ['r_momentum_ema', 'b_momentum_ema', 'BodySApM_career_dif', 'BodySApM_ema_dif', 'BodySLpM_career_dif', ...]
(_dystack pid=133158) 		('int', [])    :  3 | ['current_lose_streak_dif', 'current_win_streak_dif', 'total_fights_dif']
(_dystack pid=133158) 		('object', []) :  3 | ['division', 'total_rounds', 'b_stance']
(_dystack pid=133158) 	Types of features in processed data (raw dtype, special dtypes):
(_dystack pid=133158) 		('category', [])  :  2 | ['division', 'b_stance']
(_dystack pid=133158) 		('float', [])     : 66 | ['r_momentum_ema', 'b_momentum_ema', 'BodySApM_career_dif', 'BodySApM_ema_dif', 'BodySLpM_career_dif', ...]
(_dystack pid=133158) 		('int', [])       :  3 | ['current_lose_streak_dif', 'current_win_streak_dif', 'total_fights_dif']
(_dystack pid=133158) 		('int', ['bool']) :  1 | ['total_rounds']
(_dystack pid=133158) 	0.1s = Fit runtime
(_dystack pid=133158) 	72 features in original data used to generate 72 features in processed data.
(_dystack pid=133158) 	Train Data (Processed) Memory Usage: 1.26 MB (0.0% of available memory)
(_dystack pid=133158) Data preprocessing and feature engineering runtime = 0.13s ...
(_dystack pid=133158) AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
(_dystack pid=133158) 	To change this, specify the eval_metric parameter of Predictor()
(_dystack pid=133158) User-specified model hyperparameters to be fit:
(_dystack pid=133158) {
(_dystack pid=133158) 	'NN_TORCH': [{}],
(_dystack pid=133158) 	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
(_dystack pid=133158) 	'CAT': [{}],
(_dystack pid=133158) 	'XGB': [{}],
(_dystack pid=133158) 	'FASTAI': [{}],
(_dystack pid=133158) 	'RF': [{'criterion': 'gini', 'max_depth': 15, 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'max_depth': 15, 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'max_depth': 15, 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
(_dystack pid=133158) 	'XT': [{'criterion': 'gini', 'max_depth': 15, 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'max_depth': 15, 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'max_depth': 15, 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
(_dystack pid=133158) }
(_dystack pid=133158) AutoGluon will fit 2 stack levels (L1 to L2) ...
(_dystack pid=133158) Fitting 11 L1 models, fit_strategy="sequential" ...
(_dystack pid=133158) Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 597.37s of the 896.28s of remaining time.
(_dystack pid=133158) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=3, gpus=0, memory=0.31%)
(_dystack pid=133158) 	0.6452	 = Validation score   (accuracy)
(_dystack pid=133158) 	2.63s	 = Training   runtime
(_dystack pid=133158) 	0.04s	 = Validation runtime
(_dystack pid=133158) Fitting model: LightGBM_BAG_L1 ... Training model for up to 591.30s of the 890.21s of remaining time.
(_dystack pid=133158) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=3, gpus=0, memory=0.33%)
(_dystack pid=133158) 	0.6435	 = Validation score   (accuracy)
(_dystack pid=133158) 	4.07s	 = Training   runtime
(_dystack pid=133158) 	0.05s	 = Validation runtime
(_dystack pid=133158) Fitting model: RandomForestGini_BAG_L1 ... Training model for up to 585.36s of the 884.26s of remaining time.
(_dystack pid=133158) /home/mlioi/anaconda3/envs/ag/lib/python3.10/site-packages/sklearn/base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
(_dystack pid=133158)   warnings.warn(
(_dystack pid=133158) 	0.6267	 = Validation score   (accuracy)
(_dystack pid=133158) 	0.83s	 = Training   runtime
(_dystack pid=133158) 	0.19s	 = Validation runtime
(_dystack pid=133158) Fitting model: RandomForestEntr_BAG_L1 ... Training model for up to 584.29s of the 883.19s of remaining time.
(_dystack pid=133158) /home/mlioi/anaconda3/envs/ag/lib/python3.10/site-packages/sklearn/base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
(_dystack pid=133158)   warnings.warn(
(_dystack pid=133158) 	0.6351	 = Validation score   (accuracy)
(_dystack pid=133158) 	0.8s	 = Training   runtime
(_dystack pid=133158) 	0.19s	 = Validation runtime
(_dystack pid=133158) Fitting model: CatBoost_BAG_L1 ... Training model for up to 583.26s of the 882.17s of remaining time.
(_dystack pid=133158) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=3, gpus=0, memory=5.83%)
(_dystack pid=133158) 	0.6486	 = Validation score   (accuracy)
(_dystack pid=133158) 	12.41s	 = Training   runtime
(_dystack pid=133158) 	0.08s	 = Validation runtime
(_dystack pid=133158) Fitting model: ExtraTreesGini_BAG_L1 ... Training model for up to 569.19s of the 868.09s of remaining time.
(_dystack pid=133158) /home/mlioi/anaconda3/envs/ag/lib/python3.10/site-packages/sklearn/base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
(_dystack pid=133158)   warnings.warn(
(_dystack pid=133158) 	0.6313	 = Validation score   (accuracy)
(_dystack pid=133158) 	0.79s	 = Training   runtime
(_dystack pid=133158) 	0.19s	 = Validation runtime
(_dystack pid=133158) Fitting model: ExtraTreesEntr_BAG_L1 ... Training model for up to 568.15s of the 867.06s of remaining time.
(_dystack pid=133158) /home/mlioi/anaconda3/envs/ag/lib/python3.10/site-packages/sklearn/base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
(_dystack pid=133158)   warnings.warn(
(_dystack pid=133158) 	0.6246	 = Validation score   (accuracy)
(_dystack pid=133158) 	0.65s	 = Training   runtime
(_dystack pid=133158) 	0.18s	 = Validation runtime
(_dystack pid=133158) Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 567.28s of the 866.18s of remaining time.
(_dystack pid=133158) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=3, gpus=0, memory=0.18%)
(_ray_fit pid=136738) No improvement since epoch 2: early stopping
(_dystack pid=133158) 	0.6347	 = Validation score   (accuracy)
(_dystack pid=133158) 	6.02s	 = Training   runtime
(_dystack pid=133158) 	0.16s	 = Validation runtime
(_dystack pid=133158) Fitting model: XGBoost_BAG_L1 ... Training model for up to 559.48s of the 858.39s of remaining time.
(_dystack pid=133158) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=3, gpus=0, memory=0.88%)
(_dystack pid=133158) 	0.6507	 = Validation score   (accuracy)
(_dystack pid=133158) 	5.8s	 = Training   runtime
(_dystack pid=133158) 	0.1s	 = Validation runtime
(_dystack pid=133158) Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 551.63s of the 850.54s of remaining time.
(_dystack pid=133158) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=3, gpus=0, memory=0.10%)
(_ray_fit pid=136740) No improvement since epoch 5: early stopping [repeated 7x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#log-deduplication for more options.)
(_dystack pid=133158) 	0.6486	 = Validation score   (accuracy)
(_dystack pid=133158) 	9.13s	 = Training   runtime
(_dystack pid=133158) 	0.18s	 = Validation runtime
(_dystack pid=133158) Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 540.64s of the 839.55s of remaining time.
(_dystack pid=133158) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=3, gpus=0, memory=1.14%)
(_dystack pid=133158) 	0.6418	 = Validation score   (accuracy)
(_dystack pid=133158) 	15.29s	 = Training   runtime
(_dystack pid=133158) 	0.06s	 = Validation runtime
(_dystack pid=133158) Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 822.37s of remaining time.
(_dystack pid=133158) 	Ensemble Weights: {'XGBoost_BAG_L1': 1.0}
(_dystack pid=133158) 	0.6507	 = Validation score   (accuracy)
(_dystack pid=133158) 	0.17s	 = Training   runtime
(_dystack pid=133158) 	0.0s	 = Validation runtime
(_dystack pid=133158) Fitting 11 L2 models, fit_strategy="sequential" ...
(_dystack pid=133158) Fitting model: LightGBMXT_BAG_L2 ... Training model for up to 822.20s of the 822.19s of remaining time.
(_dystack pid=133158) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=3, gpus=0, memory=0.36%)

(_ray_fit pid=139440) [1000]	valid_set's binary_error: 0.319865

(_dystack pid=133158) 	0.6688	 = Validation score   (accuracy)
(_dystack pid=133158) 	4.35s	 = Training   runtime
(_dystack pid=133158) 	0.07s	 = Validation runtime
(_dystack pid=133158) Fitting model: LightGBM_BAG_L2 ... Training model for up to 816.07s of the 816.06s of remaining time.
(_dystack pid=133158) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=3, gpus=0, memory=0.36%)
(_dystack pid=133158) 	0.6721	 = Validation score   (accuracy)
(_dystack pid=133158) 	5.24s	 = Training   runtime
(_dystack pid=133158) 	0.06s	 = Validation runtime
(_dystack pid=133158) Fitting model: RandomForestGini_BAG_L2 ... Training model for up to 809.05s of the 809.04s of remaining time.
(_dystack pid=133158) /home/mlioi/anaconda3/envs/ag/lib/python3.10/site-packages/sklearn/base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
(_dystack pid=133158)   warnings.warn(
(_dystack pid=133158) 	0.6368	 = Validation score   (accuracy)
(_dystack pid=133158) 	0.83s	 = Training   runtime
(_dystack pid=133158) 	0.19s	 = Validation runtime
(_dystack pid=133158) Fitting model: RandomForestEntr_BAG_L2 ... Training model for up to 807.98s of the 807.98s of remaining time.
(_dystack pid=133158) /home/mlioi/anaconda3/envs/ag/lib/python3.10/site-packages/sklearn/base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
(_dystack pid=133158)   warnings.warn(
(_dystack pid=133158) 	0.6389	 = Validation score   (accuracy)
(_dystack pid=133158) 	0.82s	 = Training   runtime
(_dystack pid=133158) 	0.19s	 = Validation runtime
(_dystack pid=133158) Fitting model: CatBoost_BAG_L2 ... Training model for up to 806.93s of the 806.93s of remaining time.
(_dystack pid=133158) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=3, gpus=0, memory=6.08%)
(_dystack pid=133158) 	0.6696	 = Validation score   (accuracy)
(_dystack pid=133158) 	16.55s	 = Training   runtime
(_dystack pid=133158) 	0.1s	 = Validation runtime
(_dystack pid=133158) Fitting model: ExtraTreesGini_BAG_L2 ... Training model for up to 788.60s of the 788.60s of remaining time.
(_dystack pid=133158) /home/mlioi/anaconda3/envs/ag/lib/python3.10/site-packages/sklearn/base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
(_dystack pid=133158)   warnings.warn(
(_dystack pid=133158) 	0.6296	 = Validation score   (accuracy)
(_dystack pid=133158) 	0.66s	 = Training   runtime
(_dystack pid=133158) 	0.2s	 = Validation runtime
(_dystack pid=133158) Fitting model: ExtraTreesEntr_BAG_L2 ... Training model for up to 787.68s of the 787.68s of remaining time.
(_dystack pid=133158) /home/mlioi/anaconda3/envs/ag/lib/python3.10/site-packages/sklearn/base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
(_dystack pid=133158)   warnings.warn(
(_dystack pid=133158) 	0.6343	 = Validation score   (accuracy)
(_dystack pid=133158) 	0.67s	 = Training   runtime
(_dystack pid=133158) 	0.19s	 = Validation runtime
(_dystack pid=133158) Fitting model: NeuralNetFastAI_BAG_L2 ... Training model for up to 786.78s of the 786.77s of remaining time.
(_dystack pid=133158) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=3, gpus=0, memory=0.20%)
(_ray_fit pid=141775) No improvement since epoch 3: early stopping
(_dystack pid=133158) 	0.6494	 = Validation score   (accuracy)
(_dystack pid=133158) 	6.91s	 = Training   runtime
(_dystack pid=133158) 	0.16s	 = Validation runtime
(_dystack pid=133158) Fitting model: XGBoost_BAG_L2 ... Training model for up to 778.13s of the 778.12s of remaining time.
(_dystack pid=133158) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=3, gpus=0, memory=1.00%)
(_dystack pid=133158) 	0.6566	 = Validation score   (accuracy)
(_dystack pid=133158) 	6.79s	 = Training   runtime
(_dystack pid=133158) 	0.1s	 = Validation runtime
(_dystack pid=133158) Fitting model: NeuralNetTorch_BAG_L2 ... Training model for up to 769.41s of the 769.41s of remaining time.
(_ray_fit pid=141776) No improvement since epoch 5: early stopping [repeated 3x across cluster]
(_dystack pid=133158) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=3, gpus=0, memory=0.11%)
(_dystack pid=133158) 	0.6557	 = Validation score   (accuracy)
(_dystack pid=133158) 	13.77s	 = Training   runtime
(_dystack pid=133158) 	0.2s	 = Validation runtime
(_dystack pid=133158) Fitting model: LightGBMLarge_BAG_L2 ... Training model for up to 753.86s of the 753.85s of remaining time.
(_dystack pid=133158) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=3, gpus=0, memory=1.20%)
(_dystack pid=133158) 	0.67	 = Validation score   (accuracy)
(_dystack pid=133158) 	18.32s	 = Training   runtime
(_dystack pid=133158) 	0.09s	 = Validation runtime
(_dystack pid=133158) Fitting model: WeightedEnsemble_L3 ... Training model for up to 360.00s of the 733.72s of remaining time.
(_dystack pid=133158) 	Ensemble Weights: {'LightGBM_BAG_L2': 0.565, 'CatBoost_BAG_L1': 0.087, 'NeuralNetTorch_BAG_L1': 0.087, 'ExtraTreesGini_BAG_L1': 0.043, 'XGBoost_BAG_L1': 0.043, 'RandomForestGini_BAG_L2': 0.043, 'CatBoost_BAG_L2': 0.043, 'XGBoost_BAG_L2': 0.043, 'NeuralNetTorch_BAG_L2': 0.043}
(_dystack pid=133158) 	0.6793	 = Validation score   (accuracy)
(_dystack pid=133158) 	0.23s	 = Training   runtime
(_dystack pid=133158) 	0.0s	 = Validation runtime
(_dystack pid=133158) AutoGluon training complete, total runtime = 162.93s ... Best model: WeightedEnsemble_L3 | Estimated inference throughput: 248.7 rows/s (297 batch size)
(_dystack pid=133158) Automatically performing refit_full as a post-fit operation (due to `.fit(..., refit_full=True)`
(_dystack pid=133158) Refitting models via `predictor.refit_full` using all of the data (combined train and validation)...
(_dystack pid=133158) 	Models trained in this way will have the suffix "_FULL" and have NaN validation score.
(_dystack pid=133158) 	This process is not bound by time_limit, but should take less time than the original `predictor.fit` call.
(_dystack pid=133158) 	To learn more, refer to the `.refit_full` method docstring which explains how "_FULL" models differ from normal models.
(_dystack pid=133158) Fitting 1 L1 models, fit_strategy="sequential" ...
(_dystack pid=133158) Fitting model: LightGBMXT_BAG_L1_FULL ...
(_dystack pid=133158) 	2.19s	 = Training   runtime
(_dystack pid=133158) Fitting 1 L1 models, fit_strategy="sequential" ...
(_dystack pid=133158) Fitting model: LightGBM_BAG_L1_FULL ...
(_dystack pid=133158) 	3.03s	 = Training   runtime
(_dystack pid=133158) Fitting model: RandomForestGini_BAG_L1_FULL | Skipping fit via cloning parent ...
(_dystack pid=133158) 	0.83s	 = Training   runtime
(_dystack pid=133158) 	0.19s	 = Validation runtime
(_dystack pid=133158) Fitting model: RandomForestEntr_BAG_L1_FULL | Skipping fit via cloning parent ...
(_dystack pid=133158) 	0.8s	 = Training   runtime
(_dystack pid=133158) 	0.19s	 = Validation runtime
(_dystack pid=133158) Fitting 1 L1 models, fit_strategy="sequential" ...
(_dystack pid=133158) Fitting model: CatBoost_BAG_L1_FULL ...
(_dystack pid=133158) 	1.03s	 = Training   runtime
(_dystack pid=133158) Fitting model: ExtraTreesGini_BAG_L1_FULL | Skipping fit via cloning parent ...
(_dystack pid=133158) 	0.79s	 = Training   runtime
(_dystack pid=133158) 	0.19s	 = Validation runtime
(_dystack pid=133158) Fitting model: ExtraTreesEntr_BAG_L1_FULL | Skipping fit via cloning parent ...
(_dystack pid=133158) 	0.65s	 = Training   runtime
(_dystack pid=133158) 	0.18s	 = Validation runtime
(_dystack pid=133158) Fitting 1 L1 models, fit_strategy="sequential" ...
(_dystack pid=133158) Fitting model: NeuralNetFastAI_BAG_L1_FULL ...
(_dystack pid=133158) 	Stopping at the best epoch learned earlier - 4.
(_dystack pid=133158) 	0.78s	 = Training   runtime
(_dystack pid=133158) Fitting 1 L1 models, fit_strategy="sequential" ...
(_dystack pid=133158) Fitting model: XGBoost_BAG_L1_FULL ...
(_dystack pid=133158) 	0.38s	 = Training   runtime
(_dystack pid=133158) Fitting 1 L1 models, fit_strategy="sequential" ...
(_dystack pid=133158) Fitting model: NeuralNetTorch_BAG_L1_FULL ...
(_dystack pid=133158) 	1.93s	 = Training   runtime
(_dystack pid=133158) Fitting 1 L1 models, fit_strategy="sequential" ...
(_dystack pid=133158) Fitting model: LightGBMLarge_BAG_L1_FULL ...
(_dystack pid=133158) 	4.73s	 = Training   runtime
(_dystack pid=133158) Fitting model: WeightedEnsemble_L2_FULL | Skipping fit via cloning parent ...
(_dystack pid=133158) 	Ensemble Weights: {'XGBoost_BAG_L1': 1.0}
(_dystack pid=133158) 	0.17s	 = Training   runtime
(_dystack pid=133158) Fitting 1 L2 models, fit_strategy="sequential" ...
(_dystack pid=133158) Fitting model: LightGBMXT_BAG_L2_FULL ...
(_dystack pid=133158) 	2.37s	 = Training   runtime
(_dystack pid=133158) Fitting 1 L2 models, fit_strategy="sequential" ...
(_dystack pid=133158) Fitting model: LightGBM_BAG_L2_FULL ...
(_dystack pid=133158) 	1.04s	 = Training   runtime
(_dystack pid=133158) Fitting model: RandomForestGini_BAG_L2_FULL | Skipping fit via cloning parent ...
(_dystack pid=133158) 	0.83s	 = Training   runtime
(_dystack pid=133158) 	0.19s	 = Validation runtime
(_dystack pid=133158) Fitting model: RandomForestEntr_BAG_L2_FULL | Skipping fit via cloning parent ...
(_dystack pid=133158) 	0.82s	 = Training   runtime
(_dystack pid=133158) 	0.19s	 = Validation runtime
(_dystack pid=133158) Fitting 1 L2 models, fit_strategy="sequential" ...
(_dystack pid=133158) Fitting model: CatBoost_BAG_L2_FULL ...
(_dystack pid=133158) 	0.72s	 = Training   runtime
(_dystack pid=133158) Fitting model: ExtraTreesGini_BAG_L2_FULL | Skipping fit via cloning parent ...
(_dystack pid=133158) 	0.66s	 = Training   runtime
(_dystack pid=133158) 	0.2s	 = Validation runtime
(_dystack pid=133158) Fitting model: ExtraTreesEntr_BAG_L2_FULL | Skipping fit via cloning parent ...
(_dystack pid=133158) 	0.67s	 = Training   runtime
(_dystack pid=133158) 	0.19s	 = Validation runtime
(_dystack pid=133158) Fitting 1 L2 models, fit_strategy="sequential" ...
(_dystack pid=133158) Fitting model: NeuralNetFastAI_BAG_L2_FULL ...
(_dystack pid=133158) 	Stopping at the best epoch learned earlier - 10.
(_dystack pid=133158) 	1.04s	 = Training   runtime
(_dystack pid=133158) Fitting 1 L2 models, fit_strategy="sequential" ...
(_dystack pid=133158) Fitting model: XGBoost_BAG_L2_FULL ...
(_dystack pid=133158) 	0.36s	 = Training   runtime
(_dystack pid=133158) Fitting 1 L2 models, fit_strategy="sequential" ...
(_dystack pid=133158) Fitting model: NeuralNetTorch_BAG_L2_FULL ...
(_dystack pid=133158) 	2.58s	 = Training   runtime
(_dystack pid=133158) Fitting 1 L2 models, fit_strategy="sequential" ...
(_dystack pid=133158) Fitting model: LightGBMLarge_BAG_L2_FULL ...
(_dystack pid=133158) 	38.9s	 = Training   runtime
(_dystack pid=133158) Fitting model: WeightedEnsemble_L3_FULL | Skipping fit via cloning parent ...
(_dystack pid=133158) 	Ensemble Weights: {'LightGBM_BAG_L2': 0.565, 'CatBoost_BAG_L1': 0.087, 'NeuralNetTorch_BAG_L1': 0.087, 'ExtraTreesGini_BAG_L1': 0.043, 'XGBoost_BAG_L1': 0.043, 'RandomForestGini_BAG_L2': 0.043, 'CatBoost_BAG_L2': 0.043, 'XGBoost_BAG_L2': 0.043, 'NeuralNetTorch_BAG_L2': 0.043}
(_dystack pid=133158) 	0.23s	 = Training   runtime
(_dystack pid=133158) Updated best model to "WeightedEnsemble_L3_FULL" (Previously "WeightedEnsemble_L3"). AutoGluon will default to using "WeightedEnsemble_L3_FULL" for predict() and predict_proba().
(_dystack pid=133158) Refit complete, total runtime = 62.31s ... Best model: "WeightedEnsemble_L3_FULL"
(_dystack pid=133158) Disabling decision threshold calibration for metric `accuracy` due to having fewer than 10000 rows of validation data for calibration, to avoid overfitting (2376 rows).
(_dystack pid=133158) 	`accuracy` is generally not improved through threshold calibration. Force calibration via specifying `calibrate_decision_threshold=True`.
(_dystack pid=133158) TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/home/mlioi/ufc-predictor-v2/models/ds_sub_fit/sub_fit_ho")
(_dystack pid=133158) Deleting DyStack predictor artifacts (clean_up_fits=True) ...
Leaderboard on holdout data (DyStack):
                           model  score_holdout  score_val eval_metric  pred_time_test  pred_time_val   fit_time  pred_time_test_marginal  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0         LightGBMXT_BAG_L1_FULL       0.622896   0.645202    accuracy        0.004498            NaN   2.193995                 0.004498                     NaN           2.193995            1       True          1
1           CatBoost_BAG_L2_FULL       0.622896   0.669613    accuracy        0.486296            NaN  13.147863                 0.010770                     NaN           0.718542            2       True         17
2     ExtraTreesEntr_BAG_L1_FULL       0.616162   0.624579    accuracy        0.090645       0.184742   0.653120                 0.090645                0.184742           0.653120            1       True          7
3     ExtraTreesGini_BAG_L1_FULL       0.616162   0.631313    accuracy        0.103529       0.192155   0.793921                 0.103529                0.192155           0.793921            1       True          6
4           CatBoost_BAG_L1_FULL       0.609428   0.648569    accuracy        0.007322            NaN   1.030614                 0.007322                     NaN           1.030614            1       True          5
5     NeuralNetTorch_BAG_L1_FULL       0.606061   0.648569    accuracy        0.026998            NaN   1.932429                 0.026998                     NaN           1.932429            1       True         10
6   RandomForestGini_BAG_L1_FULL       0.606061   0.626684    accuracy        0.098121       0.190115   0.827471                 0.098121                0.190115           0.827471            1       True          3
7   RandomForestGini_BAG_L2_FULL       0.599327   0.636785    accuracy        0.569243            NaN  13.263942                 0.093717                0.186826           0.834621            2       True         15
8           LightGBM_BAG_L1_FULL       0.595960   0.643519    accuracy        0.004357            NaN   3.034774                 0.004357                     NaN           3.034774            1       True          2
9      LightGBMLarge_BAG_L2_FULL       0.592593   0.670034    accuracy        0.488471            NaN  51.329186                 0.012945                     NaN          38.899865            2       True         23
10    ExtraTreesEntr_BAG_L2_FULL       0.592593   0.634259    accuracy        0.568637            NaN  13.096084                 0.093111                0.191326           0.666763            2       True         19
11  RandomForestEntr_BAG_L2_FULL       0.589226   0.638889    accuracy        0.574281            NaN  13.244628                 0.098755                0.192146           0.815307            2       True         16
12    ExtraTreesGini_BAG_L2_FULL       0.585859   0.629630    accuracy        0.575983            NaN  13.094316                 0.100456                0.204156           0.664995            2       True         18
13      WeightedEnsemble_L3_FULL       0.585859   0.679293    accuracy        0.620019            NaN  18.185691                 0.005109                     NaN           0.229048            3       True         24
14  RandomForestEntr_BAG_L1_FULL       0.582492   0.635101    accuracy        0.098217       0.188111   0.799002                 0.098217                0.188111           0.799002            1       True          4
15    NeuralNetTorch_BAG_L2_FULL       0.579125   0.655724    accuracy        0.495175            NaN  15.005588                 0.019649                     NaN           2.576266            2       True         22
16     LightGBMLarge_BAG_L1_FULL       0.575758   0.641835    accuracy        0.008908            NaN   4.730425                 0.008908                     NaN           4.730425            1       True         11
17          LightGBM_BAG_L2_FULL       0.575758   0.672138    accuracy        0.481913            NaN  13.464576                 0.006387                     NaN           1.035255            2       True         14
18        LightGBMXT_BAG_L2_FULL       0.575758   0.668771    accuracy        0.484248            NaN  14.797105                 0.008721                     NaN           2.367784            2       True         13
19           XGBoost_BAG_L1_FULL       0.572391   0.650673    accuracy        0.012790            NaN   0.382446                 0.012790                     NaN           0.382446            1       True          9
20      WeightedEnsemble_L2_FULL       0.572391   0.650673    accuracy        0.015050            NaN   0.547495                 0.002260                     NaN           0.165049            2       True         12
21           XGBoost_BAG_L2_FULL       0.572391   0.656566    accuracy        0.484389            NaN  12.791959                 0.008862                     NaN           0.362638            2       True         21
22   NeuralNetFastAI_BAG_L1_FULL       0.565657   0.634680    accuracy        0.029050            NaN   0.781551                 0.029050                     NaN           0.781551            1       True          8
23   NeuralNetFastAI_BAG_L2_FULL       0.552189   0.649411    accuracy        0.496259            NaN  13.470569                 0.020733                     NaN           1.041248            2       True         20
	1	 = Optimal   num_stack_levels (Stacked Overfitting Occurred: False)
	232s	 = DyStack   runtime |	3368s	 = Remaining runtime
Starting main fit with num_stack_levels=1.
	For future fit calls on this dataset, you can skip DyStack to save time: `predictor.fit(..., dynamic_stacking=False, num_stack_levels=1)`
Beginning AutoGluon training ... Time limit = 3368s
AutoGluon will save models to "/home/mlioi/ufc-predictor-v2/models"
Train Data Rows:    2673
Train Data Columns: 72
Label Column:       label
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    7182.13 MB
	Train Data (Original)  Memory Usage: 1.90 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):

In [7]:
test_data = ufc_data.get_df_test()
test_data

,division,total_rounds,b_stance,r_momentum_ema,b_momentum_ema,BodySApM_career_dif,BodySApM_ema_dif,BodySLpM_career_dif,BodySLpM_ema_dif,ClinchSApM_career_dif,...,days_since_last_fight_dif,finish_rate_dif,height_dif,ko_per_fight_dif,reach_dif,reach_height_ratio_dif,sub_per_fight_dif,total_fights_dif,win_ratio_dif,label
2997,women,Three,Orthodox,-0.046875,-0.117706,0.196700,-0.004299,0.561900,1.279849,0.185800,...,581.0,-0.028,0.00,0.067,-2.54,-0.016,-0.100,9,-0.067,0
451,featherweight,Three,Orthodox,-0.765625,-0.562500,-0.129417,-0.020303,0.122500,0.085450,0.141917,...,-14.0,0.333,12.70,0.083,12.70,0.000,0.083,-2,0.000,1
2263,light heavyweight,Three,Southpaw,-0.625000,-0.638672,-0.733667,-0.340163,-0.371444,-0.265088,-0.003333,...,63.0,-0.250,-5.08,0.000,-5.08,0.001,0.000,6,0.111,1
1651,featherweight,Five,Switch,0.999622,0.984375,0.622480,0.799132,-0.756157,-1.069701,-0.146941,...,-91.0,0.333,-7.62,0.056,0.00,0.043,0.389,-12,0.167,0
292,middleweight,Three,Orthodox,-0.388672,-0.062500,0.376389,0.335522,-0.291889,-0.696125,-0.392028,...,-18.0,0.250,5.08,0.389,-5.08,-0.055,0.028,-5,0.306,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
649,light heavyweight,Five,Orthodox,0.167236,-0.763672,0.057583,-0.091291,-0.104778,-0.528207,0.109306,...,27.0,-0.750,-5.08,-0.389,-5.08,0.001,0.000,-3,-0.056,1
2261,women,Three,Orthodox,-0.546875,-0.296875,0.362167,0.578321,-0.022000,-0.180918,-0.077667,...,161.0,0.333,7.62,0.167,25.40,0.106,0.000,0,0.000,0
2069,middleweight,Three,Orthodox,0.366211,-0.414062,-0.277243,-0.476356,0.094914,0.004921,0.104529,...,-252.0,-0.096,-2.54,-0.057,-7.62,-0.027,-0.100,-3,-0.271,0
1893,women,Three,Switch,-0.359375,0.875000,0.555500,0.632454,1.058000,1.219520,0.934500,...,-90.0,0.500,-5.08,0.833,-10.16,-0.030,0.000,-3,0.667,0
1277,flyweight,Three,Southpaw,-0.519531,-0.898438,-0.212500,-0.082599,-0.070857,0.101090,-0.414464,...,27.0,-0.600,-5.08,-0.250,-5.08,-0.001,-0.125,-1,-0.339,1

In [8]:
predictor.evaluate(test_data)

{'accuracy': 0.6427503736920778,
 'balanced_accuracy': 0.6066405168435626,
 'mcc': 0.23422683890788593,
 'roc_auc': 0.6599999999999999,
 'f1': 0.48156182212581344,
 'precision': 0.5967741935483871,
 'recall': 0.4036363636363636}

In [9]:
pd.set_option('display.max_rows', None)
predictor.feature_importance(test_data)

Computing feature importance via permutation shuffling for 72 features using 669 rows with 5 shuffle sets...
	176.38s	= Expected runtime (35.28s per shuffle set)
	13.37s	= Actual runtime (Completed 5 of 5 shuffle sets)

,importance,stddev,p_value,n,p99_high,p99_low
age_dif,2.660688e-02,0.013218,0.005407,5,0.053824,-0.000610
ClinchSLpM_ema_dif,1.823617e-02,0.004011,0.000264,5,0.026495,0.009978
TD_Def_ema_dif,1.823617e-02,0.008146,0.003730,5,0.035009,0.001463
days_since_debut_dif,1.704036e-02,0.003752,0.000265,5,0.024765,0.009315
TD_Acc_ema_dif,1.584454e-02,0.007666,0.004934,5,0.031628,0.000061
SLpM_ema_dif,1.524664e-02,0.003869,0.000458,5,0.023213,0.007280
TD_Avg_career_dif,1.494768e-02,0.006253,0.002952,5,0.027823,0.002073
TStr_Acc_ema_dif,1.434978e-02,0.003600,0.000438,5,0.021762,0.006938
finish_rate_dif,1.375187e-02,0.010903,0.023903,5,0.036200,-0.008697
division,1.345291e-02,0.003506,0.000507,5,0.020671,0.006235
Sub_Avg_career_dif,1.255605e-02,0.003898,0.000985,5,0.020582,0.004530
GroundSApM_career_dif,1.225710e-02,0.006882,0.008185,5,0.026428,-0.001914
Str_Acc_career_dif,1.165919e-02,0.009881,0.028839,5,0.032005,-0.008687
BodySApM_ema_dif,1.165919e-02,0.002875,0.000410,5,0.017579,0.005739
GroundSLpM_ema_dif,1.136024e-02,0.006394,0.008252,5,0.024526,-0.001806
OpCtrlpM_ema_dif,1.106129e-02,0.005242,0.004592,5,0.021855,0.000267
Str_Def_ema_dif,1.076233e-02,0.005731,0.006853,5,0.022563,-0.001038
DistSLpM_career_dif,1.076233e-02,0.008416,0.022977,5,0.028091,-0.006566
GroundSLpM_career_dif,1.076233e-02,0.004655,0.003328,5,0.020348,0.001177
ko_per_fight_dif,1.046338e-02,0.003506,0.001310,5,0.017681,0.003245
Str_Acc_ema_dif,1.046338e-02,0.004358,0.002906,5,0.019436,0.001490
BodySApM_career_dif,1.016442e-02,0.011452,0.059088,5,0.033745,-0.013416
TStr_Acc_career_dif,1.016442e-02,0.007578,0.019984,5,0.025767,-0.005438
b_momentum_ema,1.016442e-02,0.005221,0.006063,5,0.020915,-0.000586
LegSApM_ema_dif,9.865471e-03,0.008022,0.025687,5,0.026382,-0.006651
LegSLpM_career_dif,9.566517e-03,0.005451,0.008594,5,0.020791,-0.001658
BodySLpM_ema_dif,9.267564e-03,0.003409,0.001850,5,0.016286,0.002249
Sub_Avg_ema_dif,9.267564e-03,0.003569,0.002188,5,0.016616,0.001920
DistSApM_ema_dif,8.669656e-03,0.004011,0.004220,5,0.016928,0.000411
SLpM_career_dif,8.370703e-03,0.003752,0.003775,5,0.016096,0.000646
HeadSLpM_ema_dif,8.071749e-03,0.002914,0.001727,5,0.014071,0.002072
BodySLpM_career_dif,8.071749e-03,0.005242,0.013112,5,0.018866,-0.002722
TStr_Def_ema_dif,8.071749e-03,0.004912,0.010656,5,0.018186,-0.002043
HeadSLpM_career_dif,7.772795e-03,0.005002,0.012741,5,0.018073,-0.002527
SApM_ema_dif,7.473842e-03,0.006516,0.031156,5,0.020889,-0.005942
HeadSApM_career_dif,7.473842e-03,0.004358,0.009271,5,0.016447,-0.001499
OpCtrlpM_career_dif,7.174888e-03,0.006377,0.032822,5,0.020305,-0.005955
ClinchSApM_career_dif,7.174888e-03,0.005431,0.020897,5,0.018357,-0.004007
GroundSApM_ema_dif,7.174888e-03,0.007651,0.052009,5,0.022929,-0.008579
height_dif,6.875934e-03,0.006817,0.043564,5,0.020913,-0.007161
days_since_last_fight_dif,6.576981e-03,0.009489,0.098056,5,0.026115,-0.012961
r_momentum_ema,6.576981e-03,0.005025,0.021475,5,0.016923,-0.003769
DistSLpM_ema_dif,6.576981e-03,0.004558,0.016045,5,0.015963,-0.002809
avg_time_career_dif,6.278027e-03,0.003569,0.008525,5,0.013626,-0.001070
CtrlpM_ema_dif,5.680120e-03,0.008868,0.112681,5,0.023940,-0.012580
TSLpM_ema_dif,5.680120e-03,0.005221,0.035886,5,0.016430,-0.005070
current_win_streak_dif,5.680120e-03,0.009299,0.121867,5,0.024827,-0.013466
LegSLpM_ema_dif,5.680120e-03,0.005923,0.049296,5,0.017875,-0.006515
SApM_career_dif,5.082212e-03,0.004558,0.033634,5,0.014468,-0.004304
Str_Def_career_dif,4.783259e-03,0.006289,0.082102,5,0.017732,-0.008165
TD_Acc_career_dif,4.484305e-03,0.008119,0.142194,5,0.021201,-0.012232
win_ratio_dif,4.185351e-03,0.005002,0.067351,5,0.014485,-0.006115
ClinchSApM_ema_dif,3.886398e-03,0.006217,0.117359,5,0.016688,-0.008915
LegSApM_career_dif,3.886398e-03,0.000819,0.000223,5,0.005572,0.002201
reach_dif,2.989537e-03,0.002990,0.044505,5,0.009145,-0.003166
current_lose_streak_dif,2.391629e-03,0.006567,0.230566,5,0.015913,-0.011129
DistSApM_career_dif,2.391629e-03,0.007666,0.261916,5,0.018175,-0.013392
HeadSApM_ema_dif,2.092676e-03,0.005025,0.202216,5,0.012439,-0.008253
avg_time_ema_dif,2.092676e-03,0.006651,0.260261,5,0.015788,-0.011602
b_stance,1.793722e-03,0.001949,0.054350,5,0.005807,-0.002219
ClinchSLpM_career_dif,1.793722e-03,0.006289,0.279145,5,0.014742,-0.011155
total_rounds,1.793722e-03,0.005731,0.261291,5,0.013594,-0.010007
sub_per_fight_dif,5.979073e-04,0.006394,0.422300,5,0.013764,-0.012568
reach_height_ratio_dif,2.989537e-04,0.001949,0.374434,5,0.004312,-0.003714
TD_Def_career_dif,4.440892e-17,0.006429,0.500000,5,0.013238,-0.013238
TSApM_ema_dif,2.220446e-17,0.008780,0.500000,5,0.018078,-0.018078
TD_Avg_ema_dif,-5.979073e-04,0.005348,0.592549,5,0.010413,-0.011609
TStr_Def_career_dif,-8.968610e-04,0.007444,0.599529,5,0.014430,-0.016224
CtrlpM_career_dif,-1.793722e-03,0.007122,0.698311,5,0.012870,-0.016458
total_fights_dif,-2.092676e-03,0.009311,0.679163,5,0.017079,-0.021264
TSApM_career_dif,-2.391629e-03,0.008818,0.711534,5,0.015764,-0.020548
TSLpM_career_dif,-5.082212e-03,0.004558,0.966366,5,0.004304,-0.014468

<div style="text-align: center;">
     <img src="../img/ufc_logo.png" width="800" /> 
</div>